### ISSUE TITLE
runtime: unexpected return pc for runtime.cgocallbackg called from 0x0

### ISSUE THREAD

**Issue by whd** [mozilla-services/heka#1033]
Running a pre-release build of 0.7.0 from  Tue 05 Aug 2014 09:42:42 PM UTC heka crashed with the following traceback (truncated):

    2014/08/15 04:45:52 Reload initiated.
    runtime: unexpected return pc for runtime.cgocallbackg called from 0x0
    fatal error: unknown caller pc
    
    runtime stack:
    runtime.throw(0xee79b1)
    	/usr/local/go/src/pkg/runtime/panic.c:520 +0x69 fp=0x7f4b03ffeaf8 sp=0x7f4b03ffeae0
    runtime.gentraceback(0x40dfac, 0x7f4b54498a38, 0x0, 0xc2083ce360, 0x0, 0x0, 0x7fffffff, 0x412560, 0x7f4b03ffece0, 0x5502ff4b58531000)
    	/usr/local/go/src/pkg/runtime/traceback_x86.c:180 +0xba9 fp=0x7f4b03ffebe0 sp=0x7f4b03ffeaf8
    addstackroots(0xc2083ce360, 0x7f4b03ffece0)
    	/usr/local/go/src/pkg/runtime/mgc0.c:1692 +0x168 fp=0x7f4b03ffec70 sp=0x7f4b03ffebe0
    markroot(0xc208016480, 0x26)
    	/usr/local/go/src/pkg/runtime/mgc0.c:1321 +0xbe fp=0x7f4b03ffecf0 sp=0x7f4b03ffec70
    runtime.parfordo(0xc208016480)
    	/usr/local/go/src/pkg/runtime/parfor.c:103 +0x128 fp=0x7f4b03ffed68 sp=0x7f4b03ffecf0
    runtime.gchelper()
    	/usr/local/go/src/pkg/runtime/mgc0.c:2118 +0x3f fp=0x7f4b03ffed88 sp=0x7f4b03ffed68
    stopm()
    	/usr/local/go/src/pkg/runtime/proc.c:957 +0x111 fp=0x7f4b03ffeda0 sp=0x7f4b03ffed88
    gcstopm()
    	/usr/local/go/src/pkg/runtime/proc.c:1122 +0xc4 fp=0x7f4b03ffedc0 sp=0x7f4b03ffeda0
    findrunnable()
    	/usr/local/go/src/pkg/runtime/proc.c:1163 +0x28 fp=0x7f4b03ffedf8 sp=0x7f4b03ffedc0
    schedule()
    	/usr/local/go/src/pkg/runtime/proc.c:1345 +0xe3 fp=0x7f4b03ffee20 sp=0x7f4b03ffedf8
    park0(0xc208114120)
    	/usr/local/go/src/pkg/runtime/proc.c:1410 +0xfe fp=0x7f4b03ffee40 sp=0x7f4b03ffee20
    runtime.mcall(0x407734)
    	/usr/local/go/src/pkg/runtime/asm_amd64.s:181 +0x4b fp=0x7f4b03ffee50 sp=0x7f4b03ffee40

Preliminary investigation suggests this issue might be related to https://code.google.com/p/go/issues/detail?id=7978, and in particular, [comment 9](https://code.google.com/p/go/issues/detail?id=7978#c9).

**Comment by rafrombrc** [comment]
Is this still an issue?

**Comment by whd** [comment]
Probably not, as https://github.com/golang/go/issues/7978 was fixed some time ago. Closing.
