### ISSUE TITLE
Add support for symfony / monolog

### ISSUE THREAD

**Issue by lyrixx** [mozilla-services/heka#1087]
Hello.

[Symfony](https://github.com/symfony/symfony) is PHP framwork with lot of [stars](https://github.com/stars?direction=desc&language=php&sort=stars) on github. This framework uses [monolog](https://github.com/Seldaek/monolog) as main logger. 

I write a small [blogpost](http://blog.lyrixx.info/2014/09/23/how-to-replace-logstash-by-heka-with-symfony2.html) on how integrate heka with symfony. In order to do that, I had to create a new decoder `monolog.lua`. So I wanted to know I you would be interested by a contribution of this `monolog.lua`?

(ping @Seldaek)

**Comment by lyrixx** [comment]
Unfortunately this repo is deprecated. There is no need to keep this issue open.

Anyway, thanks you for heka, it's really a good tool.

I'm a bit sad it has been deprecated without a new shiny tool.

**Comment by nickchappell** [comment]
Different project and codebase/language, but Cernan from Postmates may be of interest: https://github.com/postmates/cernan

Lots of similar ideas, even down to taking in Lua scripts, though I'm sure the interface the script has to implement or conform to is different. May still be worth your time to take a look at it though.
