### ISSUE TITLE
Emit a heka message on an output failure

### ISSUE THREAD

**Issue by placeybordeaux** [mozilla-services/heka#1103]
Currently a message that fails on output will simply be lost. Having it requeued or simply logged for future processing would be optimal, but there is no way to anticipate all the ways someone might want to recover. Having outputs emit a heka message to be reconsumed by another output would give enough flexibility to allow for whatever case is needed. This would complicate every output and potentially run the risk of an infinite loop of a failing output eating it's own failure messages, just thought I would bring up the suggestion.

**Comment by matthughes** [comment]
+1000 I'm dying to leave logstashforwarder/logstash as well but dropping logs because of a temporary blip in service is not acceptable in my situation.

**Comment by txchen** [comment]
+10000 this is really important feature.

**Comment by rafrombrc** [comment]
For anyone following, ElasticSearchOutput now supports output buffering as of #1278. Our plan is to make this available to all output plugins by 1.0 release. Closing this bug as supplanted by #1378.
