### ISSUE TITLE
ESLogstashV0Encoder - Add timestamp Format support / timestamp Issue

### ISSUE THREAD

**Issue by syepes** [mozilla-services/heka#1142]
Hello,

It would be great if we could specify the  time format of the @timestamp field, this is already possible with the ESJsonEncoder encoder

Currently the formate if forced:
```
heka/plugins/elasticsearch/encoders.go
		case "timestamp":
			t := time.Unix(0, m.GetTimestamp()).UTC()
			writeStringField(first, &buf, `@timestamp`, t.Format("2006-01-02T15:04:05.000Z"))
```

**Comment by rafrombrc** [comment]
Resolved in 28ffad108ea83f534d464138bd97c9a28752685c.
