### ISSUE TITLE
ScanForLogstreams() doesn't honor oldestDuration

### ISSUE THREAD

**Issue by hatch15** [mozilla-services/heka#1160]
When setting something like oldest_duration = "2h" in a LogStreamerInput, it ignores the setting and still processes older logs.

It seems the problem is in logstreamer/filehandling.go line 450:
```
logfiles.FilterOld(time.Now().Add(-ls.oldestDuration))
```
The filter works fine, but it returns a new set of log files which are never used.

I guess the fix is simply to change line 450 to read:
```
logfiles = logfiles.FilterOld(time.Now().Add(-ls.oldestDuration))
```
Seems to work fine for me at least, but maybe the FilterOld function should actually remove the old from the logfiles array instead?

**Comment by bigbo** [comment]
I encountered the same problem,the oldest_duration is not work.
