### ISSUE TITLE
Input plugins should write the raw data to MsgBytes

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1217]
Currently, inputs that handle protobuf messages use pack.MsgBytes and everything else writes to pack.Message.Payload (https://github.com/mozilla-services/heka/pull/1214#discussion_r21471469)
If we selected a single destination we could:
1) Get rid of some conditional code.
2) Get better use of pre-allocated memory (decrease GC is some cases)
3) Get rid of an extra allocation when sending the data to a sandbox
4) Improve preformance (slightly): testing with a simple text input passed into a sandbox decoder: MsgBytes ~4100ns, Payload ~4500ns

**Comment by rafrombrc** [comment]
Closing this b/c splitters now allow data to be written either to the message payload or to pack.MsgBytes, configurable on a per-splitter basis.
