### ISSUE TITLE
Mock of a reorganized Health Report screen

### ISSUE THREAD

**Issue by SamPenrose** [mozilla-services/heka#1227]
I manually hacked at the existing screen to generate a static mockup of a denser page:
  https://github.com/SamPenrose/mocks-heka-dasher
(you'll need the css).
The basic idea is to collapse the different kinds of plugins into a single table, with some hot 1998-style nested table action to emphasize how in/outputs flow into de/encoders. Can I get feedback on the direction?

Changes:
5 separate tables are collapsed into 3 rows of a single table, with sub-tables.
The rows in the original tables are now columns.
Links which go to pointless (?) pages are removed.
0 values are stripped.
The input prefix is stripped from decoder names, and the output prefix from encoder names.
Vertical borders are meant to indicate the flow relationship between those pairs. (I'd like to kill the light grey horizontal dividers, but they seemed impervious to my removing css rules; maybe the offending instruction is in the minified bootstrap file?).
LMK if I should share the URL for the source dashboard.

Problems:
I discarded the In Channel and Match Channel widgets. Do they need to be restored? If so, ideas?
I haven't shown 'coder "process failures" yet. Presumably that could be added next to the name if non-zero.
The result is dense and terse; maybe add tooltips or a "how to read this" block?
The HTML and CSS is amateur-hour, and of course needs to be translated to Backbone.js

**Comment by rafrombrc** [comment]
Closing since this isn't actually tracking any current work.
