### ISSUE TITLE
/etc/hekad.toml not used by default on 0.8.0 / os: debian 

### ISSUE THREAD

**Issue by exviiik** [mozilla-services/heka#1239]
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.54-2 x86_64 GNU/Linux
heka 0.8.0

hekad doesn't use /etc/hekad.toml by default as stated in the man page... You have to specify -config /etc/hekad.toml in order to startup properly.

**Comment by 4r9h** [comment]
It looks like hekad requires to specify more than 0 parameters. I'll post PR which for this, it will probably land in 0.9.0 as it changes default behaviour of hekad.

**Comment by 4r9h** [comment]
@rafrombrc  Also, maybe we should to put some kind of a sample file in /etc/hekad.toml?
