### ISSUE TITLE
is struct.pack supported in encoder?

### ISSUE THREAD

**Issue by taowen** [mozilla-services/heka#1240]
```
require "os"
require "string"
require "struct"

function process_message ()
    inject_payload("txt", "", "[ " .. struct.pack('>L', 100) .. " ]")
    return 0
end
```

xxd /var/log/test
0000000: 5b20                                     [ 
the output is truncated at "[ ", seems like there is 0 in the binary string causing the problem.

**Comment by trink** [comment]
closed by 0ad165b35a8d815122d2f2ab4dde27adb123c6f9
