### ISSUE TITLE
better decoder for nginx upstream_response_time

### ISSUE THREAD

**Issue by liyichao** [mozilla-services/heka#1251]
As http://nginx.org/en/docs/http/ngx_http_upstream_module.html#variables says:

>$upstream_response_time
keeps times of responses obtained from upstream servers; times are kept in seconds with a milliseconds resolution. Several response times are separated by commas and colons like addresses in the $upstream_addr variable.

However, heka fails to parse the log entry when it contains comma.

**Comment by trink** [comment]
closed by 0ad165b35a8d815122d2f2ab4dde27adb123c6f9
