### ISSUE TITLE
Starting hekad 0.8.1 on wheezy (7.7) fails with missing library

### ISSUE THREAD

**Issue by gcarothers** [mozilla-services/heka#1254]
```
/usr/bin/hekad: error while loading shared libraries: libGeoIP.so.1: cannot open shared object file: No such file or directory
```

0.8.0 worked perfectly fine, and there isn't anything in the change notes to point to why this might be the case.

**Comment by hauleth** [comment]
:+1: 
I have noticed it when I was trying to build Docker image based on BusyBox. It will be nice to have it as optional dep or linked statically.

**Comment by rafrombrc** [comment]
Oops. I tested this locally after purging this library from my system, I thought, but apparently I *didn't* remove the library entirely. Apologies. I'll release a 0.8.2 binary either today or tomorrow.

**Comment by hauleth** [comment]
@rafrombrc I suggest using Docker for build testing ;)
