### ISSUE TITLE
UdpInput needs parser_type even when I use raw input data

### ISSUE THREAD

**Issue by liyichao** [mozilla-services/heka#1256]
the following config is not valid:

    [UdpInput]
    address = ":8125"

I have to use:

    [UdpInput]
    address = ":9125"
    parser_type = "token"

Because I would like to parse the data in my own filter, I do not want to use any parser from heka.

Otherwise, I have to think of a delimiter.  There is "\n" in my message body, so the default is not suitable to me. I have also tried to specify "\n\n" as my delimiter of my token parser, only to find that only one byte is allowed.

**Comment by liyichao** [comment]
I encounter this when I aggregate stats like p95, mean in my application, and want to use heka to further aggregate my stats.

The message UdpInput receives is the same as `heka.statmetric ` message that heka agents sent to a central heka server:

>test.count 2 1420438130
test.count_ps 0.200000 1420438130
test.lower 1.000000 1420438130
test.upper 2.000000 1420438130
test.sum 3.000000 1420438130
test.mean 1.500000 1420438130
test.mean_95 1.500000 1420438130
test.upper_95 2.000000 1420438130

Instead of using protobuf, I use plaintext protocol like graphite's for simplificity, but the metrics are p95, max, min which do not fit in statsd' type system, so I can't use statsdInput.

The solution I choose is to use UdpInput, and write a lua filter to aggregate them. Of course, I can use "\n" as the delimiter, but that produces a message pack for every stat, which is not straightforward.

**Comment by rafrombrc** [comment]
You can work around this by using `parser_type = "regexp"` and `delimiter = '$'`, which will cause the entire UDP packet to be used as the message payload. I'm currently working on introducing 'splitters' as a new plugin type, which will replace the parser_type functionality, when that is complete there will be a NullSplitter to use in these cases.

**Comment by rafrombrc** [comment]
Closing this, splitter plugins are now available on the dev branch, using a UdpInput w/ a NullSplitter behaves as expected (i.e. the entire contents of the UDP packet are put into the payload of the message).
