### ISSUE TITLE
Invalid regexp delimiter doesn't raise an error

### ISSUE THREAD

**Issue by simonpasquier** [mozilla-services/heka#1257]
In plugins/logstreamer/logstreamer_input.go:

		if len(delimiter) > 0 {
			err = rp.SetDelimiter(delimiter)
		}
		err = rp.SetDelimiterLocation(delimiterLocation)

When rp.SetDelimiter() fails but rp.SetDelimiterLocation() is successful, the second assignment will clear the first error.

See https://github.com/mozilla-services/heka/blob/2f7dd9f5453582b7fc515e7979c0cf10e5436a7d/plugins/logstreamer/logstreamer_input.go#L479-L482

**Comment by rafrombrc** [comment]
Fixed when parser_type was replaced by splitter plugins.
