### ISSUE TITLE
Can we allow sanbox filters to inject message without timer_event ?

### ISSUE THREAD

**Issue by liyichao** [mozilla-services/heka#1264]
Use case: Modify a message and inject back to the pipeline without delay.

Now, I have to define it as an encoder. But it seems to be the function of a filter.

**Comment by rafrombrc** [comment]
SandboxFilters *can* inject a message w/o timer_event. The inject_message and inject_payload functions are available in process_message, there's nothing preventing you from using them, although if you inject more than one per input message you'll need to adjust the max_process_inject setting (see http://hekad.readthedocs.org/en/v0.8.2/config/index.html#global-configuration-options).

It should be noted, however, that SandboxFilters can only create new messages, they can't modify existing ones. Once a message gets to the router it should never be modified, b/c it might be concurrently processed by multiple filters and/or routers. Mutations would then cause race conditions.
