### ISSUE TITLE
Dashboard display

### ISSUE THREAD

**Issue by djamelfel** [mozilla-services/heka#1265]
When I try to see the dashboard page I obtain the following result 
![sans titre1](https://cloud.githubusercontent.com/assets/6094409/5649994/dc94abda-969a-11e4-8355-5f4f6acd6db8.png)
instead of
![sans titre](https://cloud.githubusercontent.com/assets/6094409/5649979/c9eae634-969a-11e4-8d74-90626bef6ded.png)

Have you any idea about my issue ?

**Comment by nlamirault** [comment]
Same behavior for me. (#1231)

**Comment by 4r9h** [comment]
Could you post your config file?

On Mon, Jan 12, 2015 at 10:01 AM, Nicolas Lamirault <
notifications@github.com> wrote:

> Same behavior for me. (#1231
> <https://github.com/mozilla-services/heka/issues/1231>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-services/heka/issues/1265#issuecomment-69542608>
> .
>



-- 
jarek@reijutsu:~$ fortune
You have Egyptian flu: you're going to be a mummy.
jarek@reijutsu:~$ fortune
You now have Asian Flu.

**Comment by djamelfel** [comment]
I try to run one more time the same configuration as previously and I'm surprise to see it's working.
