### ISSUE TITLE
getting started help for sending mem, cpu, info to influxdb without statd

### ISSUE THREAD

**Issue by steverweber** [mozilla-services/heka#1268]
I have been at it for a few hours and still haven't figured out how to send:
stats gathered from, LoadAvgDecoder, MemStatsDecoder ...
to influxdb or Carbon.

It would be really nice if an example of using these other methods to gather system data and send it off to influxdb was given instead of just statsd.

```
[loadavg]
type = "FilePollingInput"
ticker_interval = 1
file_path = "/proc/loadavg"
decoder = "LoadAvgDecoder"

[LoadAvgDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_loadavg.lua"

[LoadAvgFilter]
type = "SandboxFilter"
message_matcher = "Type == 'stats.loadavg'"
filename = "lua_filters/loadavg.lua"
ticker_interval = 1
preserve_data = true

    [LoadAvgFilter.config]
    rows = 1440
    sec_per_row = 1


[CarbonOutput]
type = "CarbonOutput"
#message_matcher = "Type == 'heka.statmetric'"
message_matcher = "TRUE"
address = "{{ vars.CarbonOutput.address }}"
protocol = "udp"

# https://hekad.readthedocs.org/en/v0.8.0/config/encoders/index.html#schema-influxdb-encoder
[influxdb]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx.lua"
    [influxdb.config]
    series = "heka.%{Logger}"
    skip_fields = "Pid EnvVersion"

[InfluxOutput]
ticker_interval = 1
message_matcher = "Type == 'heka.influxdb'"
encoder = "influxdb"
type = "HttpOutput"
address = "{{ vars.influxdb.address }}"
username = "{{ vars.influxdb.username }}"
password = "{{ vars.influxdb.password }}"
```

**Comment by ecnahc515** [comment]
Your `InfluxOutput` should have a different `message_matcher` which matches the different filters. So you could do something like `message_matcher = "Type == 'stats.loadavg'"`

**Comment by steverweber** [comment]
thanks ill try that!

**Comment by steverweber** [comment]
humm still no luck:

dashboard shows: 
LoadAvgFilter decoder and filter: processed ~100
but InfluxOutput:  processed blank

current config:
```
[hekad]
maxprocs = 2

[DashboardOutput]
ticker_interval = 1

[StatAccumInput]
ticker_interval = 1
emit_in_fields = true

[loadavg]
type = "FilePollingInput"
ticker_interval = 1
file_path = "/proc/loadavg"
decoder = "LoadAvgDecoder"

[LoadAvgDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_loadavg.lua"

[LoadAvgFilter]
type = "SandboxFilter"
message_matcher = "Type == 'stats.loadavg'"
filename = "lua_filters/loadavg.lua"
ticker_interval = 1
preserve_data = true

    [LoadAvgFilter.config]
    rows = 1440
    sec_per_row = 1


[influxdb]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx.lua"
    [influxdb.config]
    series = "heka.%{Logger}"
    skip_fields = "Pid EnvVersion"

[InfluxOutput]
ticker_interval = 1
message_matcher = "Type == 'stats.loadavg'"
encoder = "influxdb"
type = "HttpOutput"
address = "{{ vars.influxdb.address }}"
username = "{{ vars.influxdb.username }}"
password = "{{ vars.influxdb.password }}"
```

**Comment by rafrombrc** [comment]
Unfortunately there's a missing piece to closing this loop. We have an encoder that will take graphite style data (embedded in heka.statmetric messages) and serialize that into JSON suitable for InfluxDB, but we don't yet have an encoder that will serialize our cbuf time series data into InfluxDB compatible JSON. We *do* have an encoder that serializes cbuf data into Librato compatible JSON, however, see http://hekad.readthedocs.org/en/v0.8.2/config/encoders/index.html#cbuf-librato-encoder.

In order to get this done, the cbuf parsing code in the Librato encoder should be pulled out into a separate Lua module for reuse, which would then make it quite easy to write an alternate encoder that instead generates InfluxDB compatible JSON.

**Comment by steverweber** [comment]
would it be possible to send this loadavg data to the CarbonOutput plugin with the items already available in heka?

**Comment by steverweber** [comment]
```
[loadavg]
type = "FilePollingInput"
ticker_interval = 1
file_path = "/proc/loadavg"
decoder = "LoadAvgDecoder"

[LoadAvgDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_loadavg.lua"

[LoadAvgFilter]
type = "SandboxFilter"
message_matcher = "Type == 'stats.loadavg'"
filename = "lua_filters/loadavg.lua"
ticker_interval = 1
preserve_data = true
    [LoadAvgFilter.config]
    rows = 1440
    sec_per_row = 1


[CarbonOutput]
type = "CarbonOutput"
#message_matcher = "Type == 'heka.statmetric'"
message_matcher = "Type == 'stats.loadavg'"
address = "{{ vars.CarbonOutput.address }}"
protocol = "udp"
```

**Comment by steverweber** [comment]
@rafrombrc im much to new to the project to attempt creating the encoder.
I created a new issue that is more direct to the core issue.
https://github.com/mozilla-services/heka/issues/1272

thanks for helping.  I hope soon i'll beable to kick collectd to the curb : )
