### ISSUE TITLE
Setting an oversized Timestamp from Lua causes a panic()

### ISSUE THREAD

**Issue by hynd** [mozilla-services/heka#1269]
For example, the https://github.com/mozilla-services/heka/blob/b5fa9a1a82e07ec15e428deeeeb0ce01a5ae8704/sandbox/lua/decoders/graylog_extended.lua decoder does ```msg.Timestamp = json["timestamp"] * 1e9
```.  If i send JSON with a large number (ie; thinking it might be millisecond epoch), Heka panics with:

```
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x2572000 pc=0x7dcead]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7dcead
runtime.throw(0xf5f105)
        /usr/local/go/src/pkg/runtime/panic.c:520 +0x69
runtime: unexpected return pc for runtime.sigpanic called from 0x7dcead
runtime.sigpanic()
        /usr/local/go/src/pkg/runtime/os_linux.c:222 +0x3d

goroutine 65 [syscall]:
runtime.cgocallbackg()
        /usr/local/go/src/pkg/runtime/cgocall.c:244 +0x4c fp=0x7f835589bc90 sp=0x7f835589bc80
runtime.cgocallback_gofunc(0x40eaad, 0x407170, 0x7f835589bd08)
        /usr/local/go/src/pkg/runtime/asm_amd64.s:785 +0x67 fp=0x7f835589bca0 sp=0x7f835589bc90
runtime.asmcgocall(0x407170, 0x7f835589bd08)
        /usr/local/go/src/pkg/runtime/asm_amd64.s:691 +0x3a fp=0x7f835589bca8 sp=0x7f835589bca0
runtime.cgocall(0x407170, 0x7f835589bd08)
        /usr/local/go/src/pkg/runtime/cgocall.c:143 +0xfd fp=0x7f835589bcf0 sp=0x7f835589bca8
github.com/mozilla-services/heka/sandbox/lua._Cfunc_process_message(0x25578a0, 0x1ed41f85)
        github.com/mozilla-services/heka/sandbox/lua/_obj/_cgo_defun.c:112 +0x31 fp=0x7f835589bd08 sp=0x7f835589bcf0
github.com/mozilla-services/heka/sandbox/lua.(*LuaSandbox).ProcessMessage(0xc208dac000, 0xc2080734a0, 0xf7a7c0)
        /home/x/code/heka/build/heka/src/github.com/mozilla-services/heka/sandbox/lua/lua_sandbox.go:617 +0x42 fp=0x7f835589bd28 sp=0x7f835589bd08
github.com/mozilla-services/heka/sandbox/plugins.(*SandboxDecoder).Decode(0xc208d900d0, 0xc2080734a0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/x/code/heka/build/heka/src/github.com/mozilla-services/heka/sandbox/plugins/sandbox_decoder.go:262 +0x185 fp=0x7f835589be40 sp=0x7f835589bd28
github.com/mozilla-services/heka/pipeline.func·010()
        /home/x/code/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:322 +0x26b fp=0x7f835589bfa8 sp=0x7f835589be40
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445 fp=0x7f835589bfb0 sp=0x7f835589bfa8
created by github.com/mozilla-services/heka/pipeline.(*dRunner).Start
        /home/x/code/heka/build/heka/src/github.com/mozilla-services/heka/pipeline/plugin_runners.go:339 +0x112
```

**Comment by trink** [comment]
closed by 0ad165b35a8d815122d2f2ab4dde27adb123c6f9
