### ISSUE TITLE
how can we write to stderr from a lua sandbox

### ISSUE THREAD

**Issue by djamelfel** [mozilla-services/heka#1276]
I want to write some message on **stderr** if I catch an error when my plugin starts (for example when config is invalid).
I tried to use `io.stderr:write('message')`, in order to display a text message, but I couldn't import the `io` library.

What is the recommended way to log error message from heka lua sandboxes ?

**Comment by rafrombrc** [comment]
The mailing list (https://mail.mozilla.org/listinfo/heka) is a better venue for asking support questions like this. The issue tracker is for reporting bugs and making feature requests. Please resend this inquiry to the mailing list. Thanks.
