### ISSUE TITLE
statd accum input for gauge -- treat as float

### ISSUE THREAD

**Issue by rishid** [mozilla-services/heka#1280]
Statsd protocol for "gauge" type allows IEEE 754 floating point values, heka is expecting gauges to be integers only.

https://github.com/mozilla-services/heka/blob/dev/pipeline/stat_accum_input.go#L162

Various other statsd implementations parse guages as floats.

**Comment by 4r9h** [comment]
Looks like its duplicate of #850.

**Comment by rishid** [comment]
Yep, I agree did not see that one.
