### ISSUE TITLE
cjson.encode_invalid_numbers seems to have no impact

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#1281]
I'm trying to use cjson.encode_invalid_numbers in the way described in the cjson documentation, but it seems to have no impact. In [the cbuf_influx encoder](https://github.com/mozilla-services/heka/blob/cbuf_influx_encoder/sandbox/lua/encoders/cbuf_influx.lua#L124) I've tried all combinations of possible settings, but nothing seems to change the encoding behavior, I can't even get it to error if I use `false` or `off`.

**Comment by trink** [comment]
These tests are working properly for me
```lua
    local t = {0/0}

    assert(true == cjson.encode_invalid_numbers("on"), tostring(cjson.encode_invalid_numbers("on")))
    local ok, v = pcall(cjson.encode, t)
    assert(ok and v == "[NaN]", v)

    assert(true == cjson.encode_invalid_numbers(true), tostring(cjson.encode_invalid_numbers(true)))
    local ok, v = pcall(cjson.encode, t)
    assert(ok and v == "[NaN]", v)

    assert(false == cjson.encode_invalid_numbers("off"), tostring(cjson.encode_invalid_numbers("off")))
    local ok, v = pcall(cjson.encode, t)
    assert(not ok and v == "Cannot serialise number: must not be NaN or Infinity", v)

    assert("null" == cjson.encode_invalid_numbers("null"), cjson.encode_invalid_numbers("null"))
    local ok, v= pcall(cjson.encode, t)
    assert(ok and v == "[null]", v)
```

**Comment by trink** [comment]
https://github.com/mozilla-services/heka/blob/cbuf_influx_encoder/sandbox/lua/encoders/cbuf_influx.lua#L93
math.nan does not exist so you are setting it to NIL (ending the array). Use 0/0
