### ISSUE TITLE
Heka on Windows crashes when the sandbox CGO interface throws a Lua error

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1304]
Tracking: https://github.com/golang/go/issues/9754

**Comment by AT78** [comment]
Hi,

New to Heka and have had a hell of a time getting it compiled :(  will give you guys some feedback on that.

However, when trying to launch hekad.exe the program crashes with liblua.dll is not present.  Is this related to this bug at all.  I have go 1.4.1 installed.


Thanks

Andreas

**Comment by trink** [comment]
No this has nothing to do with it; but you do have to properly install it before you can run it.

**Comment by AT78** [comment]
OK, thanks Mike, i've followed
https://hekad.readthedocs.org/en/latest/installing.html to the letter.

Is there another source that can be followed to "properly install"

**Comment by AT78** [comment]
Hey Mike,

Dont worry for now, this is an environment variable problem on my machine

Thanks anyway

**Comment by abdullin** [comment]
Is this the reason why you didn't provide Windows build for 0.9.0? Can Hekad be considered as stable for Windows if used without lua plugins?

**Comment by rafrombrc** [comment]
Yes, this is the reason. At Mozilla we don't run Heka in production on Windows, and all of our Heka instances use Lua extensively, so unfortunately we can't say how stable it would be. If you experiment, we'd love to hear your results.

**Comment by abdullin** [comment]
@rafrombrc starting to roll-out heka 0.9 on Windows today. We are using it as collector daemons on Windows Azure instances. So far, it works good.

**Comment by abdullin** [comment]
FYI, rolled heka to a production Windows Azure cluster at skuvault.com last night. This deployment uses 0.9.0 with a golang plugin instead of the lua version we used before. 

No issues discovered so far.

**Comment by trink** [comment]
Fixed in Go 1.5 beta 2

**Comment by johnjelinek** [comment]
@trink: Go 1.5 is released. Will we begin to see windows binary in releases going forward now?
