### ISSUE TITLE
Add reporting for `synchronous_decode = true` decoders

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#1312]
Currently if a decoder is used in an input where the synchronous_decode setting is true, that decoder won't show up in the dashboard or in the report triggered by SIGUSR1, need to track them separately so they can be monitored.

**Comment by 4r9h** [comment]
Hi, I've read through the code as you asked on IRC.
My initial thoughts are (sorry for some oversimplifications):

    Decoders are displayed in reports because their runners are available in "global" slice called allDecoders.
    DecoderRunners register themselves in this slice and because of that reporting module can generate reports for all decoders.
    Runners implement mostly asynchronous communication via channels.
    However, deliverer reimplements part of runner functionality to provide "synchronous" feature for running decoders. That's 2 different places for "the same" thing. I think deliverer makes it a little more hidden.
    One of the first thoughts ws to provide new base interface (called e.g. DecoderBaseRunner) for runners and move current DecoderRunner into DecoderRunnerAsync and create second implementation called DecoderRunnerSync. However, i think it is overengineering.
    Second idea was to remove current code related to syncdecode from deliverer and add simple waitgroup and later pass it (together with pack via new struct) to the decoder and just .wait() until runner calls .done(). I think that's the better option to implement because leaves runners almost untouched (and the reporting layers) and don't change interfaces of existing decoders.

@rafrombrc what do you think?

**Comment by rafrombrc** [comment]
Unfortunately I don't think this is the right approach. The entire point of the synchronous_decode option is to avoid using multiple goroutines, and paying the associated syncronization and scheduling costs. Usually async decode is a better choice, but sometimes when MAXPROCS=1 synchronous decoding will be more efficient because goroutines can't be run in parallel so the cost of context switching doesn't provide any gains.

Instead I think the InputRunner should notice when a synchronous decoder is in use, and it should add the instantiated decoder to the global set of decoders so reporting will happen as it does with the async decoders.

**Comment by 4r9h** [comment]
Good point, i didn't even consider situation when there's only 1 CPU
because i thought its pretty rare in 2015 (and its not an irony from my
side).
Anyway, even if we don't want to split code in terms of goroutines, there's
still one confusing thing - AllDecoders is a slice of DecoderRunner(s). We
could (correct me if i'm wrong):
- change type of allDecoders elements from DecoderRunner to Decoder and
refactor rest of the code to reflect this change
- remove some of parts from DecoderRunner interface (or create just
separate interface for async runners) and create two implementations - sync
and async. It would separate concerns in my opinion.

On Mon, Mar 16, 2015 at 9:05 PM, Rob Miller <notifications@github.com>
wrote:

> Unfortunately I don't think this is the right approach. The entire point
> of the synchronous_decode option is to avoid using multiple goroutines, and
> paying the associated syncronization and scheduling costs. Usually async
> decode is a better choice, but sometimes when MAXPROCS=1 synchronous
> decoding will be more efficient because goroutines can't be run in parallel
> so the cost of context switching doesn't provide any gains.
>
> Instead I think the InputRunner should notice when a synchronous decoder
> is in use, and it should add the instantiated decoder to the global set of
> decoders so reporting will happen as it does with the async decoders.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-services/heka/issues/1312#issuecomment-81907775>
> .
>



-- 
jarek@reijutsu:~$ fortune
You have Egyptian flu: you're going to be a mummy.
jarek@reijutsu:~$ fortune
You now have Asian Flu.

**Comment by rafrombrc** [comment]
MAXPROCS = 1 doesn't have to mean that there's only one core, it could be that a box's primary job is something else and the admin only wants Heka to be consuming a single core.

As for the other issue, we could also just rename `allDecoders` to `asyncDRunners` (or something) and add a separate `syncDecoders` attribute to track all the synchronous decoders, the reporting code could iterate through both of them.

**Comment by 4r9h** [comment]
Re: MAXPROCS: Okay, I stand corrected. You're obviously right :) Every day i discover something new.

About ticket: I can add separate slice, but don't you think it will be DRY violation? If its not i'll start working on adding new slice for syncDecoders.

**Comment by rafrombrc** [comment]
DRY? Not sure how storing two related-but-not-identical data points in two different struct attributes can be construed as repeating ourselves. Anyway, DRY is a useful concept, but hardly an inviolable law. There are often times when repeating a small amount of code is a better idea than jumping through awkward hoops (or incurring unnecessary performance penalties) to avoid doing so.

**Comment by 4r9h** [comment]
Not identical, but in terms of concerns there's two places to where we
"run"/execute decoder. I'm outsider and i don't want to argue here - i'm
after quick marathon with this code and i probably have some different
habits.
Anyway i fully trust your judgement here.
If separate slice of decoders is final option here i'll start working on
the patch. Can i assume that similar thing should be done in #1313?

On Mon, Mar 16, 2015 at 11:08 PM, Rob Miller <notifications@github.com>
wrote:

> DRY? Not sure how storing two related-but-not-identical data points in two
> different struct attributes can be construed as repeating ourselves.
> Anyway, DRY is a useful concept, but hardly an inviolable law. There are
> often times when repeating a small amount of code is a better idea than
> jumping through awkward hoops (or incurring unnecessary performance
> penalties) to avoid doing so.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-services/heka/issues/1312#issuecomment-81962999>
> .
>



-- 
jarek@reijutsu:~$ fortune
You have Egyptian flu: you're going to be a mummy.
jarek@reijutsu:~$ fortune
You now have Asian Flu.
