### ISSUE TITLE
AMQP input binding to readonly exchange

### ISSUE THREAD

**Issue by asanami** [mozilla-services/heka#1314]
I'm trying to set up an AMQP input to an exchange that I only have read permissions to.  It seems the default behaviour is to declare an exchange, which requires readwrite permissions.  It is possible to simply bind to the exchange, if so, its not obvious how to do this from the documentation.

This is my current configuration:
```
[AMQPInput]
url = "amqp://user:password@amqp.company.com/VHOST"
exchange = "MyExchange"
exchange_type = "topic"
exchange_durability = true
exchange_auto_delete =  false
routing_key = "#"
queue = "test"
decoder = "json_decoder"
```

Thanks
Alex

**Comment by ioc32** [comment]
+1

I had the same issue when I first started setting it all up. Eventually, I
decided to move on and provide dedicated users with slightly more
permissions than strictly necessary.

Our setup could use an iteration now, so I am also interested in learning
how to get heka to use readonly users.

**Comment by mattrco** [comment]
I've approached this in #1322. Please take a look - this works for my use case, but I'm sure there are exchange/queue configurations that I haven't anticipated.
