### ISSUE TITLE
LogstreamerInput + PayloadRegexDecoder and multi-line log messages?

### ISSUE THREAD

**Issue by zyro** [mozilla-services/heka#1319]
Is it possible to process multi-line log output using `LogstreamerInput` and `PayloadRegexDecoder`?

For example the log lines:
```
2015-02-07 [info] testing
2015-02-07 [error] problem
  ...stack trace here...
```

With a regex like `^(?P<Timestamp>.*) \\[(?P<Severity>[a-z]+)\\] (?P<Message>.*)` I get a failure trying to parse the 3rd line.

Is there a way to match across multiple lines?

**Comment by zyro** [comment]
OK, made some progress by switching my `LogstreamerInput`'s `parse_type` to `regexp` with a pattern that looks like `(?P<Timestamp>[0-9]{4}-[0-9]{2}-[0-9]{2})` to match the beginning of a log message.

Problem now is the `Message` match group only seems to contain the first line, the rest seem to disappear...

**Comment by trink** [comment]
The mailing list (https://mail.mozilla.org/listinfo/heka) is a better venue for asking support questions like this. The issue tracker is for reporting bugs and making feature requests. Please resend this inquiry to the mailing list. Thanks.
