### ISSUE TITLE
Sandbox read_message("raw") should get the current encoding of the Heka message

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1342]
When a message is mutated it needs to be re-encoded before being consumed by read_message("raw").

1) Encoding on demand means that the same message may be re-encoded several times by filters and encoders (like we currently have happening now for every protobuf output).  Or we need to introduce a lock on the pack/message so we can safely update the MsgBytes once and flag that it is current. https://github.com/mozilla-services/heka/issues/265

2) Always encoding mutated messages before the router can create extra overhead (especially if the raw message isn't consumed).  However, in our current production environment this should actually reduce the CPU load on our system by avoiding the multiple encoding we are performing now.

I vote for option 2

**Comment by rafrombrc** [comment]
Resolved in #1406.
