### ISSUE TITLE
Kafka and Protobuf

### ISSUE THREAD

**Issue by carlanton** [mozilla-services/heka#1349]
Hi!

I spent hours to get ```KafkaOuput --> KafkaInput``` work together with ProtobufEncoder/ProtobufDecoder.

Finally I found out that I need to configure the KafkaInput with a NullSplitter with use_message_bytes = true:
```
[KafkaInput]
topic = "logs"
addrs = ["localhost:9092"]
splitter = "MySplitter"
decoder = "ProtobufDecoder"

[MySplitter]
type = "NullSplitter"
use_message_bytes = true # <--- This was required!
```

The KafkaOutput config looks like this:
```
[KafkaOutput]
message_matcher = "TRUE"
topic = "logs"
addrs = ["localhost:9092"]
encoder = "ProtobufEncoder"
```

Maybe we could set this as the default splitter for KafkaInput?

**Comment by ecnahc515** [comment]
Not all people use kafka with protobuf, so that wouldn't make a lot of sense.

**Comment by carlanton** [comment]
That's true, but I guess it's a pretty common use case? Maybe some documentation about it would be sufficient...

**Comment by ecnahc515** [comment]
What about http://hekad.readthedocs.org/en/latest/config/splitters/index.html#common-splitter-parameters

Could that use clarification, or is it unclear how to use `use_msg_bytes` from that?

**Comment by carlanton** [comment]
Sorry for my rudeness, I know all these features are very new!

I started from the examples on http://hekad.readthedocs.org/en/latest/config/inputs/kafka.html and http://hekad.readthedocs.org/en/latest/config/outputs/kafka.html. I realize now that the input example is from before the splitters.

**Comment by ecnahc515** [comment]
Ah yes, it would probably be useful to have examples specifically using a few various inputs/ouputs that are using protobuf decoders/encoders to help with this.

**Comment by carlanton** [comment]
Maybe something like #1350?

**Comment by ecnahc515** [comment]
That seems reasonable, and useful.
