### ISSUE TITLE
LogstreamerInput infinite loop

### ISSUE THREAD

**Issue by mart1nl** [mozilla-services/heka#1367]
The LogstreamerInput in 0.9.0 seems to fall into an infinite loop when it encounters a line
greater than MAX_RECORD_SIZE and just starts spamming the following message:
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped
2015/02/26 17:39:27 Input 'LogstreamerInput' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped

Can be reproduced with the following testfile:
(dd if=/dev/zero of=/dev/stdout count=70000 bs=1 | tr '\0' 'w') > testdata

**Comment by jaredgisin** [comment]
What is the timing on getting this fix out into 0.9.1 ? I'm hitting this issue.

**Comment by rafrombrc** [comment]
0.9.1 will be released tomorrow. You can build from the versions/0.9 branch to get the fix sooner if needed.

**Comment by DanyC97** [comment]
i am on 0.10.b1 and i still get this issue, what am i missing?

**Comment by Meeral** [comment]
Seeing this problem on 0.10.b1 as well

**Comment by sbward** [comment]
@rafrombrc I ran into this issue today on 0.10.b1, please re-open the issue :v:

**Comment by rafrombrc** [comment]
Unfortunately, I can't reproduce this error. Originally I could reproduce using the 'testdata' as suggested in the issue, but then #1369 fixed the issue and it's no longer happening. I've tried a few different variations (multiple lines that were too long, long lines interspersed with short lines, etc.) but no matter what I do Heka doesn't misbehave. I'm doing this using versions/0.10 branch.

For those of you still seeing the issue, can you try using the 'testdata' as specified above to see if that still causes the issue. I won't be able to do anything about it until I can understand exactly what circumstances are causing the problem.
