### ISSUE TITLE
Evaluate usage of pure Go LUA interpreter

### ISSUE THREAD

**Issue by nightlyone** [mozilla-services/heka#1368]
Gopher LUA provides a pure Go implementation of a LUA VM at https://github.com/yuin/gopher-lua

Using it would simplify build and deploy of heka a lot.

**Comment by rafrombrc** [comment]
One of the major benefits of using Lua is the wide array of existing libraries available, many of which are written in C and will only work with Lua or LuaJIT. A number of the existing Lua modules that we've written for use within our sandbox are also written in C. Switching to a less mature implementation that eliminates many of the benefits of our current environment is a non-starter.

**Comment by nightlyone** [comment]
Thx for clearing this up. I remembered the embedded Lua interpreter only be used for fast prototyping and ad-hoc scripting of plugins. I agree with your other use cases in mind my suggestions makes no sense.
