### ISSUE TITLE
support for InfluxDB tags

### ISSUE THREAD

**Issue by lubko** [mozilla-services/heka#1383]
When writing to InfluxDB, hostname should be encoded as a metrics tag instead of value
http://influxdb.com/blog/2015/02/24/influxdb-v0_9_0-rc4_released_now_with_tags_and_more_unicorns.html

Option to define additional static tags, ie region, would be also nice.

**Comment by acesaro** [comment]
I've already started working on this and was going to start another issue about building out support for the InfluxDB 0.9.0 API changes.  @rafrombrc, I've started a new issue for tracking the InfluxDB 0.9.0 API update support that I will link to this one.  All of the new functionality for InfluxDB 0.9.0+ (including support for tags) I have posed in: https://github.com/mozilla-services/heka/issues/1387

**Comment by lubko** [comment]
superseded by #1387
