### ISSUE TITLE
Add InfluxDB v0.9.0+ API support and features

### ISSUE THREAD

**Issue by acesaro** [mozilla-services/heka#1387]
When upgrading to the upcoming 0.9.0 release of InfluxDB, there are some major changes occurring in the API to write and read data to/from the database via HTTP.  There is also strong support and encouragement for the use of tags for improved query and aggregation capabilities.  The new API call structure for writing data to InfluxDB 0.9.0+ is documented here: http://influxdb.com/docs/v0.9/concepts/reading_and_writing_data.html#writing-data-using-the-http-api

This issue is to track progress on the upgrades to the InfluxDB encoders (Schema InfluxDB Encoder and StatMetric InfluxDB Encoder) and potentially adding a decoder for supporting the periodic querying of data from InfluxDB into Heka messages for various purposes.

Here are the proposed updates up for discussion.  I have already started building them using this as a plan, but I would appreciate any input on any better ways to implement.

* Add a new optional boolean config option called `post_v09_api` that switches the logic throughout the script that generates the message structure to support the InfluxDB 0.9.0+ API.  This will default to false to maintain the existing functionality by default.
* Add a new optional config option `database` that defines the database that the output of the encoders is destined to within InfluxDB.  This was formerly embedded in the `address` config option for the encoders but needs to be split out as it is part of the API call now.  As a result, the example values for `address` will be updated in documentation for InfluxDB 0.9.0 endpoints.
* Add a new optional config option `retention_policy` which will map to the retentionPolicy attribute in the InfluxDB 0.9.0 API call.
* Add a new optional config option `map_fields_as_tags` that automatically maps fields (base and dynamic) in the Heka message that make sense to be used as tags (e.g. non-numerical values).
* Add a new optional config option `tag_fields` that allows the explicit definition of fields to be included as tags, overriding the `map_fields_as_tags` option when it is defined as true.
* Potentially add a new config option `timestamp_precision` that formats the timestamp appropriately in the write API message.  This would have values that match what InfluxDB accepts (n, u, ms, s, m, and h) and does the math on the timestamp value accordingly.
* Potentially add a new decoder InfluxDB Query Decoder which takes the JSON in the response to an InfluxDB 0.9.0+ query request and injects a Heka message into the pipeline for desired routing.  The potential use case here is taking the result of an HTTP input which runs an aggregate query periodically and then routes it to filters to potentially use anomaly detection or routing to another monitoring system.

Let me know your thoughts on this proposal.  As I mentioned, I've started working on this already as some of it is absolutely necessary for InfluxDB 0.9.0+, but other items can be changed where it makes sense for the project.

**Comment by rafrombrc** [comment]
Thanks for tackling this, and for explaining your ideas in such detail! My thoughts on what you've proposed:

* The changes from 0.8 to 0.9 are significant enough that it probably doesn't make sense to try to clutter up a single encoder's code base with both implementations. I'd say scrap the `post_v09_api` setting and just implement the new stuff as a separate encoder.
* Given that, `database` should no longer be an optional setting.
* `retention_policy` would remain optional.
* I'm starting to think maybe we've taken the wrong approach by having an `exclude_base_fields` setting, and that you might be following that up with the `map_fields_as_tags` setting. Instead, it might make sense to just have `skip_fields` and `tag_fields` settings, but to allow a couple of "magic" values such as `**all_base**` (for both) and `**all**` (for `tag_fields` only). Need to also think about how `skip_fields` and `tag_fields` interact with each other.
* `timestamp_precision` seems reasonable.
* A decoder for InfluxDB query responses also seems reasonable, but deserves a separate ticket.

Hope this is useful.

**Comment by acesaro** [comment]
Thanks for the feedback!  I'm going to start on a new encoder called "Schema InfluxDB Write Encoder," named for the new "write" API that InfluxDB 0.9.0 exposes.  All of your input makes sense and I will run with it for implementation.

In your spirit of keeping the configuration and functionality of the encoders simple, I'm also going to make `multi_series` the default behavior, since the "batching" of data sent to InfluxDB is highly encouraged to improve the performance of the ingestion.  Instead of the Heka fields being sent as additional attributes like they were in "Schema InfluxDB Encoder" without `multi_series = true`, they will just become tags of all points in this new encoder.

In addition, the config option `series` will be renamed to `name` for more native mapping to the attribute of the JSON object we are generating and sending to the API.

We should also consider functionality in the future to spool and batch more metrics together which would result in a smaller amount of larger calls to the InfluxDB write API (which is documented to improve performance).  I think that is out of scope for this initial work, though.

**Comment by acesaro** [comment]
I've submitted the new Schema InfluxDB Write Encoder, which implements the initial functionality to send metrics to an InfluxDB 0.9.0+ instance via the write API.  I have tested this successfully with the Heka configuration embedded in the Lua script, sending the load average values polled from /proc/loadavg into separate series in InfluxDB.  This was tested against a local instance of InfluxDB 0.9.0, git commit 11a908f.

Let me know your thoughts and how we go about testing this further.  If this is the only functionality that we want to add in this issue, I can open separate issues to update StatMetric InfluxDB Encoder and add InfluxDB Query Decoder.

**Comment by inthecloud247** [comment]
what do you think about adding message batching functionality also?

**Comment by acesaro** [comment]
@inthecloud247, are you referring to some functionality that I mentioned above: "We should also consider functionality in the future to spool and batch more metrics together which would result in a smaller amount of larger calls to the InfluxDB write API (which is documented to improve performance). I think that is out of scope for this initial work, though."?  I think it's outside the scope of the encoder and better suited as a filter, but maybe @rafrombrc can chime in here about that.

**Comment by rafrombrc** [comment]
Yes, I think this is outside the scope of the encoder. Batching is best done in either a filter or, in some cases, as a part of the output itself.

Also, closing this issue since the write encoder has been merged. We can open other issues to track any additional pieces if necessary.
