### ISSUE TITLE
Strange error with ElasticSearchOutput plugin after upgrading to 0.9.0: "Message too big"

### ISSUE THREAD

**Issue by abdullin** [mozilla-services/heka#1389]
After upgrading from 0.8.3 to 0.9.0 we started getting this error in our logs:

    2015/03/05 06:17:57 Plugin 'ElasticSearchOutput' error: Message too big, requires 96813 (MAX_MESSAGE_SIZE = 65536)

ElasticSearchOutput doesn't have `MAX_MESSAGE_SIZE` setting, as I understand. Where does the error originate from?

Our config looks like this:

```
[ESJsonEncoder]
index = "%{Type}-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"

[ElasticSearchOutput]
type="ElasticSearchOutput"
message_matcher = "(Type != 'stat_metric')"
server = "http://localhost:9200"
flush_interval = 5000
flush_count = 10
encoder = "ESJsonEncoder"
```

**Comment by trink** [comment]
ElasticSearchOutput now uses buffered output which does enforce max_message_size.  You will have to update your configuration to allow for larger messages. https://hekad.readthedocs.org/en/latest/config/index.html#global-configuration-options.

**Comment by abdullin** [comment]
Thanks a lot for the answer!
