### ISSUE TITLE
Retry config not being honoured on ProcessInputs

### ISSUE THREAD

**Issue by hynd** [mozilla-services/heka#1395]
Similar to #1117, some of the retry configs aren't working quite as expected.

With 0.8.3, the ```max_retries``` config is being ignored, a ProcessInput gets respawned indefinitely.  This basic config reproduces it:
```
[ProcessInput]
ticker_interval = 0
[ProcessInput.command.0]
bin = "/bin/false"
[ProcessInput.retries]
max_retries = 5
```
It seems like the ```rh.Reset()``` on L244 of 
https://github.com/mozilla-services/heka/blob/0c64368a0e328e6d02d0f919ffab6e7fe26aa279/pipeline/plugin_runners.go#L244 is knobbling both ```times``` and ```curDelay```.
```r.times``` is always set back to 0 and never exceeds ```r.retries``` in ```rh.Wait()```.

0.9 has a couple of separate problems.  The first is that (with the same config as above), a ProcessInput halts forever.
It looks like the process_input.go's ```once``` mutex (https://github.com/mozilla-services/heka/blob/b8c60547f3505d385d73b48ba55f8058950e3a3c/plugins/process/process_input.go#L147) doesn't get reset on ```Init()```, so when the plugin_runners.go retry loop re-```Init()```'s the plugin and comes round a second time to ```Run()```, the ProcessInput's stopChan doesn't get closed by ```Stop()``` and just waits.
If i add in a reset of the ```pi.once``` in ```Init()```, the respawn works.

Also, r.times is still getting clobbered by a moved ```rh.Reset()``` at https://github.com/mozilla-services/heka/blob/b8c60547f3505d385d73b48ba55f8058950e3a3c/pipeline/plugin_runners.go#L287, so it doesn't honour ```max_retries``` either.
(there's now a condition around the Reset(), but ProcessInput's ```Run()``` looks like it'll always return nil).

**Comment by rafrombrc** [comment]
Thanks for the detailed bug report! I've verified that the sync.Once issue, will make sure it's resolved in next week's 0.9.1 release.

The other issue seems to be the result of some ambiguity on what `max_retries` means, exactly. The current behavior is assuming that if the plugin fails to start (i.e. `Init()` returns an error) then the retry count should increment, but if the plugin actually initializes and starts then it's considered a success and the retry count is reset. The docs aren't specific on this, however, and it's not clear that this is more useful than your interpretation, which is that the retry count should continue to increment regardless of whether or not the plugin is successfully restarted. I'll see about changing things so your use case can be met, will try to get that into 0.9.1 also.

**Comment by rafrombrc** [comment]
Okay, I've changed the ProcessInput to consider an early (i.e. pre-Heka shutdown) exit of a process when ticker_interval is set to 0 to be an error. This matches what the documentation implies, and should have a side effect of causing the RetryHelper not to reset its retry count. This is on the versions/0.9 branch, is it possible for you to test and verify?

**Comment by hynd** [comment]
Works good on ProcessInputs where ticker_interval = 0, though see #1412
