### ISSUE TITLE
ElasticSearchOutput shuts down heka because of invalid checkpoint

### ISSUE THREAD

**Issue by abdullin** [mozilla-services/heka#1404]
Our heka gateway installation (ubuntu 14 LTS running heka 0.9.0 from the package) hits an issue with the cache of `ElasticSearchOutput`, which brings hekad completely down. It appears that checkpoint file somehow points to the older file that no longer exists (already dequeued maybe).

Creating empty cache file lets heka continue.

Logs:

```
2015/03/10 06:12:46 Plugin 'ElasticSearchOutput' error: open /var/cache/hekad/output_queue/ElasticSearchOutput/61119.log: no such file or directory
2015/03/10 06:12:46 Plugin 'ElasticSearchOutput': stopped
2015/03/10 06:12:46 Plugin 'ElasticSearchOutput': has stopped, shutting down.
```
`cat checkpoint.txt`:
```
61119 111964
```
`ls`:
```
61120.log  61128.log  61136.log  61144.log  61152.log  61160.log
61121.log  61129.log  61137.log  61145.log  61153.log  61161.log
61122.log  61130.log  61138.log  61146.log  61154.log  61162.log
61123.log  61131.log  61139.log  61147.log  61155.log  61163.log
61124.log  61132.log  61140.log  61148.log  61156.log  61164.log
61125.log  61133.log  61141.log  61149.log  61157.log  checkpoint.txt
61126.log  61134.log  61142.log  61150.log  61158.log
61127.log  61135.log  61143.log  61151.log  61159.log
```

**Comment by rafrombrc** [comment]
Does this happen spontaneously while Heka is running, or did this happen when coming back up after a restart?

**Comment by abdullin** [comment]
AFAIK, we notice this error when Heka comes back from the restart. Happened ~3 times in ~1 week.

**Comment by rafrombrc** [comment]
Okay, I've dug into the [relevant code](https://github.com/mozilla-services/heka/blob/dev/pipeline/buffered_output.go#L245) and am confused about how this is happening. The line of code that I linked to is the only place where buffer files are being deleted. Immediately after the file is removed, the new checkpoint file is being written. The only way I can see that we'd end up with a missing log file like you're describing is if the `Remove` call is successful but the immediately following `writeCheckpoint` call is failing. If that's true, though, the entire ElasticSearchOutput should be exiting, which would show up in the logs and, most likely, cause Heka to shut down.

I'm hoping you can provide more information about what set of circumstances are causing this issue. Are you seeing Heka crash at all? Is it exiting cleanly? Are there any indications in your log files that something is going wrong? It'd be easy enough to work around to the issue, but I really want to make sure we understand what's going on before throwing kludgey solutions at the problem.

Thanks.

**Comment by abdullin** [comment]
We investigated that. It could be caused by a bug in our own configuration. Because of the cron-job gone wild, heka was restarting every minute for an hour. Repeat that multiple times a day, and there is a decent chance of getting ACK on "Remove" but then failure on the checkpoint.

Fixing that config issue should reduce the probability of that ever happening again to a negligible amount.

**Comment by rafrombrc** [comment]
Hrm. I'm glad to hear that you're able to fix something in your setup to minimize / effectively eliminate this problem, but it's not immediately clear to me how shutdowns, even if they're happening far more often than they should, can land us in this situation. I'd like to understand exactly what's happening, so I hope you don't mind me digging a little deeper.

There is a [select statement on L224](https://github.com/mozilla-services/heka/blob/v0.9.1/pipeline/buffered_output.go#L224) that is checking for shutdown, in the form of closure of the buffer's stopChan. If we get past this point, then there isn't any other place in the code where a shutdown sequence would interrupt the execution until a possible [retry wait loop on L272](https://github.com/mozilla-services/heka/blob/v0.9.1/pipeline/buffered_output.go#L272), or until the next iteration of the outer loop comes around.

So AFAICT a shutdown signal shouldn't interrupt Heka between the file remove and the checkpoint write. What would cause this result is if the file remove is succeeding but the checkpoint write operation is failing and returning an error, but it's not clear to me how a shutdown signal might trigger a write failure. If there is a write failure, that should be making its way to the logs. Were you seeing any output in the logs before or during shutdown, prior to the restart failures, that indicate that the checkpoint write was failing?

**Comment by abdullin** [comment]
I'm sorry. We never encountered this issue since then. 

However, could some other part of the code (e.g. badly written plugin) terminate the runtime without requesting a proper shutdown? Physical machine shutdown, if it happens at unlucky point in time, could probably cause that as well.

**Comment by rafrombrc** [comment]
Yes, a `kill -9`, a panic, or some other hard crash could cause hit at exactly the wrong moment and leave you with the file missing but the checkpoint still pointing to it. That seems rare enough to not likely happen multiple times in a single week, though.

Anyway, I guess I'll (unsatisfyingly) close this issue. Thanks for your feedback. :)

**Comment by abdullin** [comment]
Could high disk IO increase the chance of hitting this issue?

**Comment by sanga** [comment]
It appears that we have just hit this bug in production. Yesterday we had a box hard lock up (I'm still not entirely sure what happened - kernel problem or hypervisor problem maybe) and after bringing the machine back up, heka hits the error message described above when starting and immediately shuts down again
