### ISSUE TITLE
Maybe a bug in cmd/heka-logstreamer

### ISSUE THREAD

**Issue by chzyer** [mozilla-services/heka#1436]
Hi, sorry to bother you guys.
I'm reading the source on `cmd/heka-logstreamer/main.go` .
In the function `parseConfig`(line: 123), I found what the source code follows:

```{go}
	if len(config.FileMatch) > 0 && config.FileMatch[len(config.FileMatch)-2:] != "$" {
		config.FileMatch += "$"
	}
```

I think that `config.FileMatch[len(config.FileMatch)-2:]` could never be equals with "$" !
Is that a bug? Please let me know if I'm wrong, Thanks!

**Comment by rafrombrc** [comment]
Yup, that's a typo. I've just pushed a fix, will open a PR for it now. Thanks for catching it!
