### ISSUE TITLE
Expose `disable_modules` in Sandbox config

### ISSUE THREAD

**Issue by tdavis** [mozilla-services/heka#1442]
Now that the Lua Sandbox default config disables the io module, the only way I am aware of to enable it (and feel free to correct me!) is to write my own ``SandboxFoo`` plugins that use a variation on ``CreateLuaSandbox`` to pass a different config string into ``lsb_create_custom()``. It would be nice if I could override the ``disable_modules`` (and ``remove_entries``!) in the same way I can override anything else in ``SandboxConfig``.

**Comment by trink** [comment]
This is an intentional Heka design decision.  The sandbox configuration has always disabled the I/O module in everything but the Input/Output sandbox plugins.  All I/O from the other plugin types must use the sandbox API so it can be monitored.
