### ISSUE TITLE
Packet-based inputs drop records w/ no trailing delimiter

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#1455]
If a packet-based input is used with a TokenSplitter and there's no delimiter at the end of the message then the last record in the message will be dropped. If there's no delimiter in the message at all, then an error will be returned since no record will be found. For instance, if an AMQPInput using a TokenSplitter with `,` as the delimiter receives a message containing `this,is,a,set,of,records`, then `records` will be dropped. If it contains `this is a single record` then an error will be raised. This is unexpected, ideally we'd at least default to considering the trailing content to be a record.

**Comment by 4r9h** [comment]
Hi, i can start working on this. Can we treat strings without delimiters as a incomplete data? [similarily to handling data in streams]  We would  pass them without delimiter appended at the end?

**Comment by rafrombrc** [comment]
Resolved in #1480.
