### ISSUE TITLE
Extract graphite generation code into reusable module

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#1461]
I wrote a simple filter to extract some data from http request messages and generate graphite formatted output to help a user on the mailing list, available at https://gist.github.com/rafrombrc/3858a7885e766fbefa61. Most of the code in the timer_event function should be extracted from that filter and packaged up as callable functions to make it easier to generate graphite formatted stats in the future.

**Comment by 4r9h** [comment]
I'm pasting directions provided by @rafrombrc on #heka channel:
```
<RaFromBRC> the idea would be to end up with a `graphite.lua` module that lives here: https://github.com/mozilla-services/heka/tree/dev/sandbox/lua/modules
<RaFromBRC> mainly i want to be able to pass in a bucket name, an interval (measured in seconds), and either a single value (for counts) or an array of values (for timers)
<RaFromBRC> the return value would be a string containing all of the graphite formatted lines for that stat
```
