### ISSUE TITLE
[Question] Recommended solution to monitor system status

### ISSUE THREAD

**Issue by txchen** [mozilla-services/heka#1465]
Like CPU/memory/disk, etc.
If we use heka agent on the server, what's the recommended way to collect system metric like cpu/mem/disk?

Thanks!

**Comment by brokenjacobs** [comment]
We use a system called diamond to push these stats via statsd.

https://github.com/BrightcoveOS/Diamond

Otherwise you could use one of the input decoders Heka has now, or a seperate system like collectd.

**Comment by txchen** [comment]
@brokenjacobs thanks! I will take a look.

Actually I am wondering can heka itself provide this kind of feature? Then we only need one agent for system metric collecting, log shipping, and custom metric collecting, that sounds clean, right?

**Comment by ecnahc515** [comment]
Heka does provide this kind of feature. Using a [file polling input](http://hekad.readthedocs.org/en/latest/config/inputs/file_polling.html) on one of the supported proc files (like `/proc/stat`) in combination with the appropriate decoders/filters (like the [CPU stats decoder] (http://hekad.readthedocs.org/en/latest/config/decoders/linux_cpu_stats.html)/[CPU stats filter](http://hekad.readthedocs.org/en/latest/config/filters/cpu_stats.html)) you can gather system metrics. Right now only basic cpu/memory/disk stats are available, though.
