### ISSUE TITLE
[Question] Guidance on an l2met to influxdb pipeline

### ISSUE THREAD

**Issue by bmarini** [mozilla-services/heka#1467]
I have app logs that are currently outputting [l2met style](https://github.com/ryandotsmith/l2met/wiki/Usage#logging-convention) metrics. I'd like to leverage heka as much as possible to get these metrics into influxdb downstream.

I've read the documentation on following plugins:

* [Stat Accumulator Input](http://hekad.readthedocs.org/en/latest/config/inputs/stataccum.html)
* [Stat Filter](http://hekad.readthedocs.org/en/latest/config/filters/stat.html)
* [Schema InfluxDB Write Encoder](http://hekad.readthedocs.org/en/latest/config/encoders/schema_influx_write.html)

I thought I might be able to write a filter/decoder to convert my l2met style log messages into messages that the `Stat Filter` understands, but my issue here is that I don't know my stats up front, they need to be dynamic. I want my apps to be able to emit new stats and not have to update my heka configuration.

My next thought is that I can write a  plugin that does what the `Stat Filter` does, taking my l2met style messages as input and creating `Stat` objects for the `Stat Accumulator Input` to consume.

Alternatively, I could ignore the `Stat Filter` and `Stat Accumulator Input` plugins, and write a custom filter
to do the parsing and aggregation and emit messages for the `Schema InfluxDB Write Encoder` to consume.

Anything I end up writing I'd like to contribute back to heka if possible, so looking for some advice on what plugin I should write that would be most in line with heka's design.

**Comment by rafrombrc** [comment]
Hi! Thanks for the detailed question, and for being willing to contribute your work back. First, I should say that generally the [mailing list](https://mail.mozilla.org/listinfo/heka) is a better venue for questions such as this than the issue tracker, which is more focused on keeping track of bugs and feature requests.

To quickly answer your question, however, the third option is definitely what I would recommend. The StatFilter works, but for a number of reasons is not very efficient so it would likely fall behind if the throughput starts to pick up. Anyway, if InfluxDB is your target, there's not much value in generating stats data in the graphite format, so I don't see why we'd want to get the StatAccumInput involved at all.

If I were doing this, I'd probably write some Lua code to do the parsing and deploy that in a SandboxDecoder, and then a bit more code to do the aggregating and deploy that in a SandboxFilter. Not knowing the stats up front shouldn't be a problem. As long as you can write a grammar to describe the format that the stats are in, you can parse them and extract whatever information they contain.

This isn't exactly what you want, but I recently wrote an example [SandboxFilter](https://gist.github.com/rafrombrc/3858a7885e766fbefa61) that listens for specific data in a Heka message and periodically generates graphite format aggregations of that data, to replace a StatFilter / StatAccumInput setup that was running too slowly. Your details are different, but the basic pattern of receiving data in the `process_message` function, storing it in data structures, and then periodically emitting that aggregate data in a new message in the `timer_event` function would be the same. Hopefully you find that somewhat useful.

Good luck!

**Comment by bmarini** [comment]
Thanks for the detailed reply! This is extremely helpful.
