### ISSUE TITLE
Request: LuaSandbox should export fields

### ISSUE THREAD

**Issue by tdavis** [mozilla-services/heka#1500]
I was just about done implementing my own ``SandboxFilter`` (I want to control ``disable_modules`` and ``remove_entries`` via the config file) when I realized I'd need to copy the entire ``lua_sandbox.go`` file and export all my own C functions because none of the fields on ``LuaSandbox`` are exported. If they were exported, I could embed the struct and avoid all the craziness.

(As it stands, I'm already patching ``lua_sandbox.go.in`` during my CMake run, so it's not a huge departure to export them using that same method, but I'd love to avoid patches where possible)

**Comment by tdavis** [comment]
Okay, so I forgot that the C types are "namespaced" at build time so instead of creating my own package named "lua" my final patch to ``lua_sandbox.go.in`` looks like this:

```diff
diff --git a/sandbox/lua/lua_sandbox.go.in b/sandbox/lua/lua_sandbox.go.in
index 50e8d92..6101725 100644
--- a/sandbox/lua/lua_sandbox.go.in
+++ b/sandbox/lua/lua_sandbox.go.in
@@ -683,6 +684,26 @@ func CreateLuaSandbox(conf *sandbox.SandboxConfig) (sandbox.Sandbox, error) {
 	return lsb, nil
 }
 
+func CreateLuaSandboxCustom(conf *sandbox.SandboxConfig, tpl string) (sandbox.Sandbox, error) {
+	lsb := new(LuaSandbox)
+	lsb.sbConfig = conf
+	cs := C.CString(conf.ScriptFilename)
+	defer C.free(unsafe.Pointer(cs))
+	ccfg := C.CString(tpl)
+	defer C.free(unsafe.Pointer(ccfg))
+	lsb.lsb = C.lsb_create_custom(unsafe.Pointer(lsb), cs, ccfg)
+	if lsb.lsb == nil {
+		return nil, fmt.Errorf("Sandbox creation failed")
+	}
+	lsb.injectMessage = func(p, pt, pn string) int {
+		log.Printf("payload_type: %s\npayload_name: %s\npayload: %s\n", pt, pn, p)
+		return 0
+	}
+	lsb.config = conf.Config
+	lsb.globals = conf.Globals
+	return lsb, nil
+}
+
 func (this *LuaSandbox) Init(dataFile string) error {
 	csDataFile := C.CString(dataFile)
 	csPluginType := C.CString(this.sbConfig.PluginType)

```
Certainly much safer than extern'ing a bunch of unsafe fields and now my package doesn't require cgo either :+1:

**Comment by trink** [comment]
The modules and entries that are disabled in filters are done so for very specific reasons.  They should not be generically customizable.
