### ISSUE TITLE
lua cjson.decode fails to parse valid JSON inside of sandbox decoder

### ISSUE THREAD

**Issue by avinson** [mozilla-services/heka#1504]
see bottom of message for JSON blob. if I read the blob directly from a file in a lua script and run cjson.decode, the blob will parse fine. However, if I read from heka (via logstreamerinput, udpinput, etc.) and run the following:
```lua
raw_message = read_message("Payload")
local ok, json = pcall(cjson.decode, raw_message)
```
It will fail.. taking out the pcall to gain more insight, you will get the following error:

Expected value but found invalid token at character 1

It would seem the first character in raw_message is not a { but something else.

example input config:
```yaml
[jsonlog]
type = "LogstreamerInput"
log_directory = "/var/log"
file_match = 'json\.log'
decoder = "json_decoder"
```
where json.log is the contents of the blob below

example decoder config:
```yaml
[json_decoder]
type = "SandboxDecoder"
script_type = "lua"
filename = "lua_decoders/json.lua"
```
decoder source: https://gist.github.com/jveldboom/763556cdba6a012843d7

JSON blob:
```json
{"acctSubject":"","authBackend":"hub","environment":"production","grantedAccess":[{"type":"repository","name":"touk/ctrl-pkw","action":"pull"}],"http.request.host":"auth.docker.io","http.request.id":"51eedc45-7818-44f4-a448-85524329bb78","http.request.method":"GET","http.request.remoteaddr":"52.6.134.97","http.request.uri":"/token?scope=repository%3Atouk%2Fctrl-pkw%3Apull\u0026service=registry.docker.io","http.request.useragent":"docker/1.6.0 go/go1.4.2 git-commit/4749651 kernel/3.16.0-0.bpo.4-amd64 os/linux arch/amd64","http.response.contenttype":"application/json","http.response.duration":"28.032627ms","http.response.status":200,"http.response.written":1442,"level":"info","msg":"getToken complete","requestedAccess":[{"type":"repository","name":"touk/ctrl-pkw","action":"pull"}],"service":"garant","signingKeyID":"VPGO:PFG7:EECI:WEOI:6FZG:KCJS:JSDL:UF7Q:G5HA:2L7Q:4BAA:OA3U","time":"2015-04-29T21:13:46Z"}
```

**Comment by avinson** [comment]
the issue can be worked around with the following code:
```lua
raw_message = read_message("Payload")
local m = string.sub(raw_message, 2)
local ok, json = pcall(cjson.decode,m)
```

**Comment by trink** [comment]
I am not seeing it fail on the parse (please check your json.log), for me it is failing on the inject_message.  You cannot put arbitrary JSON into message.Fields.  It has to conform to https://hekad.readthedocs.org/en/latest/sandbox/index.html#lua-message-hash-based-field-structure.
