### ISSUE TITLE
Standardize all time format strings on strftime

### ISSUE THREAD

**Issue by trink** [mozilla-services/heka#1508]
#1469 Addressed the file output but we also use the native Go time format string in 
the payload encoder, elasticsearch and sandbox input/decoders.

**Comment by 4r9h** [comment]
@trink i can take this ticket if you agree.

**Comment by trink** [comment]
@4r9h +1

**Comment by 4r9h** [comment]
@trink @rafrombrc i've started working on this and after more evaluation of go-strftime. Jehiah's implementation doesn't support all switches from strftime.org which can be

**Comment by 4r9h** [comment]
I've chosen fastly/go-utils because they've implemented most of the modifiers from strftime.org.
Unfortunately, it looks like that none of these libraries (fastly/go-utils and cactus/gostrftime) support %f modifier (which is required by some of ES tests).
I'll try to fix it in upstream or create my own fork.
@rafrombrc @trink I think we should revert changes from previous PR because it doesn't make a sense to release it until i'm done with this issue.

**Comment by eldondev** [comment]
I am new to heka, but I thought I would chime in here with an outside opinion. A highly modifiable switch for formatting fractional seconds seems a bit excessive, and might overcomplicate the matter. It seems reasonable to me to use `%f` for microseconds (like python), and `%N` for nanoseconds (this is what my `date` does, I don't know why Joey glosses over it) . It seems pretty unlikely that one would need much more resolution than that, and it supplies simplicity at the cost of perfect adherence to c's `strftime` implementation. I would recommend maybe making a pull request to one (or both) of the two projects you mentioned to support it. I may work on that as well if I can hack it out.

**Comment by jotes** [comment]
@eldondev yeah, you're right. I've discussed that matter some time ago with @rafrombrc on irc and final decision was to drop support for nanoseconds. I've updated PR in meantime and its probably finished, it requires only final review from @rafrombrc or @trink .

**Comment by trink** [comment]
https://github.com/mozilla-services/heka/pull/1550

**Comment by mikn** [comment]
@jotes Hi! You mention that you were dropping support for nanoseconds, but that seems to also have meant that you didn't include support for microseconds, nor milliseconds. But neither of the libraries you mention actually support anything more detailed than seconds.
For us it would be nice to have support for nano/micro/milli-seconds, not for ordering logs among servers, but at least on the server itself.
I found this go-library that implements %n with an optional offset, so you can decide the number of decimals: https://github.com/hhkbp2/go-strftime
In general, though, it doesn't seem very difficult to send an upstream patch to the selected strftime-library either: http://godoc.org/github.com/cactus/gostrftime - but there's always the risk of it not being accepted.
