### ISSUE TITLE
[ProcessInput] capture return code

### ISSUE THREAD

**Issue by rishid** [mozilla-services/heka#1511]
For ProcessInput and ProcessDirectoryInput input plugins, is it possible to capture the return code of the process that gets executed?

I could then start using Nagios-like scripts and have heka execute my check_* scripts and then alert if rc == 2

**Comment by rafrombrc** [comment]
I'd love to support this. Unfortunately, it's quite a bit trickier than you might expect. First, ProcessInput supports piping multiple commands together, so you'd have to make sure you handle all of the cases where an error happens somewhere along the chain. Second, and more importantly, process return codes don't work similarly across all platforms.

Even so, it would be possible to check whether the user is on a Unix-like OS, and, if so, capture the exit code from the last executed process in the chain, storing it in a message field for any stdout and/or stderr messages that are generated. It's a bit of work, though, and it's not at the top of our priority queue right now, so it will either have to wait a bit or be done by an outside contributor.

**Comment by imormo** [comment]
I am working on this feature for my current project. 
I will contribute my implementation back.
