### ISSUE TITLE
output kafka,definition topic is error

### ISSUE THREAD

**Issue by bigbo** [mozilla-services/heka#1517]
my toml is:

```
[test_output]
type = "KafkaOutput"
message_matcher = "TRUE"
topic = "%Logger%"
addrs = ["192.9.1.102:9092"]
encoder = "PayloadEncoder"
```

run is error:
```
Plugin '_test_output' error: Unknown error, how did this happen? Error code = 17
```

I think the problem is `topic = "%Logger%"`, I do not know ` "% Logger%" ` did not get value.
please help me .

**Comment by trink** [comment]
See https://hekad.readthedocs.org/en/latest/config/outputs/kafka.html#kafka-output
You want to use `topic_variable`

**Comment by bigbo** [comment]
@trink  thx.
