### ISSUE TITLE
KafkaInput plugin dropping messages

### ISSUE THREAD

**Issue by uohzxela** [mozilla-services/heka#1559]
We are using KafkaInput plugin for one of our data pipelines recently. We found out that some of the messages are dropped upon testing the data input & output. Initially we thought the problem lies with our plugins, however after some troubleshooting, we have traced it back to KafkaInput plugin. 

Here's how we found out: we modified the kafka_input.go in Heka's source directory to output messages so that we can track if messages are indeed dropped by KafkaInput real-time. We then used Postman to send requests to an API server, which sends the request logs to a Kafka topic using KafkaOutput plugin. The outcome confirms our suspicion. 

Here's a self-explanatory video that shows the whole process (left terminal is output from KafkaInput, right terminal is output from tailing the Kafka logs): https://www.dropbox.com/s/iekaewyy7lxdv0y/kafka_input_bug.mp4?dl=0

KafkaInput TOML file:

```
[hotels-rates-input-kafka]
type = "KafkaInput"
topic = "analytics-visits"
addrs = ["kafka-a-1.bezurk.org:9092", "kafka-b-1.bezurk.org:9092"]
```

Appreciate it if anyone can solve this problem!

**Comment by Elemecca** [comment]
@uohzxela over at the Sarama issue, you said:
>We do have 2 partitions, the problem lies with the fact that KafkaOutput plugin (Sarama producer) is producing to either one of the partitions randomly (the default setting for the partitioner is Random), and we are only consuming from one partition. I changed the Kafka config to have only one partition and it works now. Closing this issue since the problem lies with our Kafka config, not with Sarama. 

Shouldn't this issue also be closed, since you've fixed your problem?

**Comment by uohzxela** [comment]
Yes, thanks for reminding me. I have forgotten about this issue. Closing this now.
