### ISSUE TITLE
tcpoutput plugin reconnecting seems not working

### ISSUE THREAD

**Issue by liyichao** [mozilla-services/heka#1571]
When I stop heka server, heka agent shows:

```
2015/06/02 21:40:08 Plugin 'TcpOutput' error: writing to heka_server:9126: write tcp heka_server_ip:9126: broken pipe
```

But when I start heka server, first there is not any message saying it is ok. Secondly, my statsd data is lost (tcpdump captures no data), and that is why I doubt tcp output plugin is not working as expected. When I restart heka agent, statsd data comes back.

**Comment by liyichao** [comment]
Sorry. It seems my problem.

**Comment by Fydot** [comment]
Aoh~
