### ISSUE TITLE
is there a syslogd UDP decoder and encoder?

### ISSUE THREAD

**Issue by steverweber** [mozilla-services/heka#1573]
I have found a syslogd decoder... but it does not seem to be UDP friendly.

the BSD format seems simple.
www.ietf.org/rfc/rfc3164.txt
```
<13>Feb  5 17:32:18 10.0.0.99 Use the BFG!
<34>Oct 11 22:14:15 mymachine su: 'su root' failed for lonvick on /dev/pts/8
```

if this is not already done I might take a stab at it.

**Comment by trink** [comment]
The mailing list (https://mail.mozilla.org/listinfo/heka) is a better venue for asking questions like this. The issue tracker is for reporting bugs and making feature requests. Please direct future queries there, thanks.

Here is the configuration I used/tested on my system.
``` toml
[hekad] # Heka 0.9
maxprocs = 4

[RsyslogUdpInput] 
type = "UdpInput" 
splitter = "NullSplitter"
address = ":5559" # adjust according to your syslog config
decoder = "RsyslogDecoder" 

[RsyslogDecoder] 
type = "SandboxDecoder" 
script_type = "lua" 
filename = "lua_decoders/rsyslog.lua" 

   [RsyslogDecoder.config] 
   # traditional_forward_format
   template = '<%PRI%>%TIMESTAMP% %HOSTNAME% %syslogtag:1:32%%msg:::sp-if-no-1st-sp%%msg%' 
   tz = "America/Los_Angeles" 

[RstEncoder]

[LogOutput]
message_matcher = "TRUE"
encoder = "RstEncoder"
