### ISSUE TITLE
alert not found

### ISSUE THREAD

**Issue by haf** [mozilla-services/heka#1578]
Trying the Getting-Started docs on 0.10.

```
2015/06/22 12:40:47 Error making runner for stat_graph: Initialization failed for 'stat_graph': Init() /usr/share/heka/lua_filters/stat_graph.lua:85: module 'alert' not found:
	no file '/usr/share/heka/lua_modules/alert.lua'
	no file '/usr/share/heka/lua_modules/alert.so'
```

Because it's in `/usr/share/heka/lua_encoders`

I don't know lua so I can't fix the import. Is the intro to this project wrong?

**Comment by rafrombrc** [comment]
Yes, there were some final steps left out of the instructions for the source build. I've updated the docs and have opened a PR (see #1579). I'll close this issue once those get merged and the docs are available on readthedocs.org.

**Comment by rafrombrc** [comment]
The updated docs are now showing up on readthedocs.org: http://hekad.readthedocs.org/en/dev/installing.html

**Comment by haf** [comment]
@rafrombrc Sweet! =)
