### ISSUE TITLE
Heka fails to build on win7(32bit)

### ISSUE THREAD

**Issue by tianlin** [mozilla-services/heka#1582]
lua_sandbox is a very good feature, but it make build heka too hard.
two issues:
1). when it comes to build lua_sandbox under win7(32bit):
CMake Error at src/CMakeLists.txt:35 (install):
  install DIRECTORY does not allow "COMPONENT" after PATTERN or REGEX.
2). I rewrite src/CMakeLists.txt:35 to   
install(DIRECTORY "${EP_BASE}/bin/"  DESTINATION lib COMPONENT core PATTERN "*.dll" )
and rebuild again:

[ 22%] Performing build step for 'lua_bloom_filter'
Scanning dependencies of target bloom_filter
Building C object CMakeFiles/bloom_filter.dir/lua_bloom_filter.c.obj
Linking C shared module bloom_filter.dll
C:\yottabyte_heka\build\ep_base\Build\lua_sandbox\ep_base\lib\libluasb.dll.a: er
ror adding symbols: Archive has no index; run ranlib to add one
collect2.exe: error: ld returned 1 exit status
CMakeFiles\bloom_filter.dir\build.make:115: recipe for target 'bloom_filter.dll'
 failed
mingw32-make[8]: *** [bloom_filter.dll] Error 1
CMakeFiles\Makefile2:927: recipe for target 'CMakeFiles/bloom_filter.dir/all' fa
iled
mingw32-make[7]: *** [CMakeFiles/bloom_filter.dir/all] Error 2
Makefile:142: recipe for target 'all' failed
mingw32-make[6]: *** [all] Error 2
CMakeFiles\lua_bloom_filter.dir\build.make:108: recipe for target 'ep_base/Stamp
/lua_bloom_filter/lua_bloom_filter-build' failed
mingw32-make[5]: *** [ep_base/Stamp/lua_bloom_filter/lua_bloom_filter-build] Err
or 2
CMakeFiles\Makefile2:962: recipe for target 'CMakeFiles/lua_bloom_filter.dir/all
' failed
mingw32-make[4]: *** [CMakeFiles/lua_bloom_filter.dir/all] Error 2
Makefile:142: recipe for target 'all' failed
mingw32-make[3]: *** [all] Error 2

**Comment by runner-mei** [comment]
update your cmake to newest.

**Comment by tianlin** [comment]
@runner-mei , I use cmake-3.3.0-rc3, the problem is still there. At last I  fix it by this:
1.modify src/CMakeLists.txt:35 to
install(DIRECTORY "${EP_BASE}/bin/"  DESTINATION lib COMPONENT PATTERN "*.dll")
2.modify build/ep_base/Source/lua_sandbox/cmake/externals.cmake:66 to 
INSTALL_ARGS "install"

**Comment by runner-mei** [comment]
i try it on win32, it already crash with lua_sandbox. don't run it on win32
