### ISSUE TITLE
LogstreamerInput: the Logstream base file should be always the newest one.

### ISSUE THREAD

**Issue by mareklobaza** [mozilla-services/heka#1587]
For sorting with ascending order, the base file is set as oldest one thus the new messages are waiting till the next rotation. The base file should be always threat as newer one!

Log structure:
```
Bus.log
Bus.log00003
Bus.log00002
Bus.log00001
```
For configuration:
```
[input_heka]
type = "LogstreamerInput"
log_directory = "/var/logs"
file_match = 'Bus\.log?(?P<Index>\d*)'
priority = ["Index"]
```
heka-logstreamer:
```
Logstream name: [input_heka]
Files: 4 (printing oldest to newest)
        /var/logs/Bus.log
        /var/logs/Bus.log00001
        /var/logs/Bus.log00002
        /var/logs/Bus.log00003
```

**Comment by rafrombrc** [comment]
You can get around this by setting up a translation map for the "Index" value to map the "missing" value to the highest possible value, e.g. 99999. Details and an example config are in the [Logstreamer docs](http://hekad.readthedocs.org/en/dev/pluginconfig/logstreamer.html#mappings-with-missing-values).
