### ISSUE TITLE
Documentation for message_matcher uses double not single quotes for examples

### ISSUE THREAD

**Issue by AdeMiller** [mozilla-services/heka#1611]
https://hekad.readthedocs.org/en/v0.9.2/message_matcher.html

> Type == “test” && Severity == 6
> (Severity == 7 || Payload == “Test Payload”) && Type == “test”
> Fields[foo] != “bar”

Should read

> Type == 'test' && Severity == 6
> (Severity == 7 || Payload == 'Test Payload') && Type == 'test'
> Fields[foo] != 'bar'

Single not double quotes.

**Comment by trink** [comment]
Both single and double quotes are allowed: 
https://hekad.readthedocs.org/en/v0.9.2/message_matcher.html#quoted-string
