### ISSUE TITLE
Doesn't build from a release tarball

### ISSUE THREAD

**Issue by damz** [mozilla-services/heka#1615]
The build process currently insists on being run under a `git` checkout. This means that building from a source release tarball doesn't actually work at all:

```shell
$ TARGET=heka-tmp ; rm -Rf $TARGET ; mkdir $TARGET && curl -s -L https://github.com/mozilla-services/heka/archive/v0.9.2.tar.gz | tar xz --strip-components=1 -C $TARGET && cd $TARGET && . build.sh

-- The C compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Found Go: /usr/bin/go (found suitable version "1.5", required is "1.3") 
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- GeoIP.h was not found, GeoIP functionality will not be included in this build.
-- Docker plugins enabled.
-- Found Hg: /usr/bin/hg (found version "version 2.2.2") 
fatal: Not a git repository (or any of the parent directories): .git
CMake Error at CMakeLists.txt:108 (message):
  Failed to init Heka submodules


-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.

```

**Comment by trink** [comment]
https://github.com/mozilla-services/heka/pull/1555#issuecomment-106945680

**Comment by damz** [comment]
Not a very big annoyance, but a bug nonetheless, especially if you want to be included in distributions down the road. What about leaving this issue open and looking into fixing it?

**Comment by rafrombrc** [comment]
Did you read the comment that was linked above? We have no intention nor desire to provide a source tarball release, but the github releases UI exposes such a link and there's no way we can remove it. I'll happily provide support to anyone who is interested in generating an official Heka package for any widely used distro, but we don't plan on spending any cycles on fixing a source tarball download that is outside of our control.
