### ISSUE TITLE
StatAccumInput plugin doesn't support multi PercentThreshold

### ISSUE THREAD

**Issue by i19** [mozilla-services/heka#1621]
I'm using statsd to aggregate data then send to graphite. I'm trying to translate to Heka. 
But i found heka StatAccumInput plugin doesn't support setting multi PercentThreshold which statsd support it as a list type. 
And i do really need it to judge whether the most cases are infected or only a few . 
Thanks

**Comment by rafrombrc** [comment]
Resolved in #1631.
