### ISSUE TITLE
output_queue is not rolled

### ISSUE THREAD

**Issue by Bloodevil** [mozilla-services/heka#1627]
I upgrade to 0.10 version and then output queue is not rolled. 

my configuration is like below
        [Output_under1000.buffering]
            max_file_size = 26843546  # 256MiB
            full_action = "block"
            cursor_update_count = 100

but output_queue/Output_under1000/1.log is bigger then 256MiB.
So I checked pipeline/queue_buffer.go and found code like below.

        160        if bf.writeFileSize+uint64(len(pack.MsgBytes)) > maxQueueFileSize {

this bf.writeFileSize is not updated in any queue_buffer.go file. after I add code like below, RollQueue() function worked.

        writeFileInfo, _ := bf.writeFile.Stat()
        bf.writeFileSize = uint64(writeFileInfo.Size())
        if bf.writeFileSize+uint64(len(pack.MsgBytes)) > maxQueueFileSize {

please let me know when bf.writeFileSize is assigned.

**Comment by AlexTsr** [comment]
I can confirm that the issue exists and that the above fix solves it for 0.10.0b1

**Comment by rafrombrc** [comment]
Fixed in #1682.
