### ISSUE TITLE
Add Hostname from UdpInput and TcpInput

### ISSUE THREAD

**Issue by sathieu** [mozilla-services/heka#1668]
I have a FreeBSD machine sending syslog without the Hostname. But it is known from the source IP.

I've not found a generic way to do this (see http://golang.org/pkg/net/).

How to then?

**Comment by rafrombrc** [comment]
Your best option, by far, is to fix your data source.

There's no way to do what you want, currently. I'd be open to considering a contribution where the plugins optionally add a message field containing the remote address. This would need to happen in the pack decorator and, as such, would only apply when use_message_bytes is not set to true. Then it would be possible to use a decoder to copy the remote address value to the hostname field.

Or, you could fix your data source.

**Comment by sathieu** [comment]
Replaced by #1670.
