### ISSUE TITLE
0.10.0(b1 and b0) build fails

### ISSUE THREAD

**Issue by rvzanten** [mozilla-services/heka#1674]
I am using go1.4.linux-amd64
So at some point it does:
```
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Install scripts: /home/builder/heka/cmake/CMakeDebHelperInstall.cmake
CPack: - Install script: /home/builder/heka/cmake/CMakeDebHelperInstall.cmake
CMake Error at /home/builder/heka/cmake/CMakeDebHelperInstall.cmake:10 (file):
  file COPY cannot find "/home/builder/heka/build/debian/heka".


CPack Error: Error when generating package: heka
make[3]: *** [CMakeFiles/deb] Error 1
make[2]: *** [CMakeFiles/deb.dir/all] Error 2
make[1]: *** [CMakeFiles/deb.dir/rule] Error 2
make: *** [deb] Error 2
mv: cannot stat '*.deb': No such file or directory
```
And then it stops.

I checked out the following file : 
https://github.com/mozilla-services/heka/blob/v0.10.0b1/cmake/CMakeDebHelperInstall.cmake

and i see it tries to directly execute the 'heka' file in the 'debian' dir, which doesnt exist in here:

https://github.com/mozilla-services/heka/tree/v0.10.0b1/debian

It should call heka.init i guess?
I am not a developer of heka but i am trying to get a docker image working that depends on heka.
It was still using version 0.9.0 which got broken cause of the code.google.com reference which returned a status 502. But now the newest version (0.10.0b1 or 0.10.0b0) doesnt work cause of the problem described above. Also the master branch doesnt work since it still works with 0.9.2 which contains the nasty code.google.com 502 bug.

**Comment by sathieu** [comment]
@rvzanten What is your Debian version? Works for me on wheezy and jessie (with source build.sh; make deb).

Have you purged the "build" directory and retried?

**Comment by rvzanten** [comment]
Iam using jessie.  And it removes the entire container where it builds after the build fails or succeeds so i guess if i try again it will start with a clean environment.
Well maybe the the difference is that i call a custom build.sh. Though, it doesn't differ that much from the original heka build.sh.

This build.sh looks like this:
```
#!/usr/bin/env bash

# set up our environment
. ./env.sh

NUM_JOBS=${NUM_JOBS:-1}

# build heka
mkdir -p $BUILD_DIR
cd $BUILD_DIR
cmake -DCMAKE_BUILD_TYPE=release ..
make -j $NUM_JOBS deb
mv -v *.deb $HOME/
```
Let me know what you think.

**Comment by rvzanten** [comment]
Also, when i try to build 0.10.0b1 manually on a local enviorment using the same custom build script defined above; it also doesnt work and triggers the same error i get when doing it via Docker.

**Comment by sathieu** [comment]
Can you try:
```
#!/usr/bin/env bash

# set up our environment
. ./env.sh

NUM_JOBS=${NUM_JOBS:-1}

# build heka
mkdir -p $BUILD_DIR
cd $BUILD_DIR
cmake -DCMAKE_BUILD_TYPE=release ..
make -j $NUM_JOBS
make deb
mv -v *.deb $HOME/
```

**Comment by rvzanten** [comment]
Yes that works. Thank you very much @sathieu .
