### ISSUE TITLE
Does flushing payload reducing message size?

### ISSUE THREAD

**Issue by s00** [mozilla-services/heka#1675]
Hi. I'm trying to count just number of appeared logs.

Some of logs are too big and I got error:
Input 'service-command' error: record exceeded MAX_RECORD_SIZE 65794 and was dropped

But I want to count them too. 
I tried to resolve this by flushing payload using decoder.message_fields
but still have same error. 

Is that expecting behavior?

Here part of my config:

    [PayloadRegexDecoder]
    type = "PayloadRegexDecoder"
    match_regex = '^(.+)'
    
    [PayloadRegexDecoder.message_fields]
    Payload = "truncated"
    
    [service-command]
    type            = "LogstreamerInput"
    decoder         = "PayloadRegexDecoder"
    log_directory   = '/var/www/service/log'
    file_match      = '(?P<CmdName>.+)\.log'
    differentiator  = ["service.", "CmdName"]

    [counter]
    type = "StatFilter"
    message_matcher = "Logger =~ /^service/"

    [counter.Metric.values]
    type = "Counter"
    name = "%Logger%.%Hostname%"
    value = "1"

Thanks!

**Comment by DanyC97** [comment]
@s00 have you found a way ?

**Comment by trink** [comment]
The available options are:
1. Truncate the message see: https://hekad.readthedocs.org/en/latest/config/splitters/index.html#common-splitter-parameters
2. increase the max_message_size see:
https://hekad.readthedocs.org/en/latest/config/index.html#global-configuration-options
3. count the record exceeded error messages (you would have to parse the Heka log) and add them to the the total count)

**Comment by s00** [comment]
@DanyC97 I did not.

I was trying Trink's first solution, but keep_truncated=true produces multiple number of records from big one, which is not what i'm expecting. May be i do something wrong.

Another solutions are not appropriate to me.

If you will find a way, please share your method with me:)
Good luck!
