### ISSUE TITLE
HelloWorld TCP string input

### ISSUE THREAD

**Issue by ChristianKniep** [mozilla-services/heka#1683]
Hey y'all,

I would like to get used to heka in order to include it in my software stack and get rid of rsyslog as relay mechanism.
To do so I would expect to send a simple string to a TCP port and this will be wrapped with some meta value and off I go.

But somehow I miss something, I would expect heka to consume `echo "helloworld"|nc -w1 127.0.0.1 514` if I configure it like this:
```
# cat /etc/hekad.toml.simple
[hekad]
maxprocs = 2

[TcpInput]
address = ":514"
decoder = "string-input-decoder"

[string-input-decoder]
type = "PayloadRegexDecoder"
match_regex = '^(?P<Message>.*)'

[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"
```
But if I do so the decoder stopped which I interpret as failed.
```
/opt/heka/bin/hekad -config=/etc/hekad.toml.simple
2015/08/19 16:10:28 Pre-loading: [string-input-decoder]
2015/08/19 16:10:28 Pre-loading: [PayloadEncoder]
2015/08/19 16:10:28 Pre-loading: [LogOutput]
2015/08/19 16:10:28 Pre-loading: [DashboardOutput]
2015/08/19 16:10:28 Pre-loading: [TcpInput]
2015/08/19 16:10:28 Pre-loading: [NullSplitter]
2015/08/19 16:10:28 Loading: [NullSplitter]
2015/08/19 16:10:28 Pre-loading: [ProtobufDecoder]
2015/08/19 16:10:28 Loading: [ProtobufDecoder]
2015/08/19 16:10:28 Pre-loading: [ProtobufEncoder]
2015/08/19 16:10:28 Loading: [ProtobufEncoder]
2015/08/19 16:10:28 Pre-loading: [TokenSplitter]
2015/08/19 16:10:28 Loading: [TokenSplitter]
2015/08/19 16:10:28 Pre-loading: [HekaFramingSplitter]
2015/08/19 16:10:28 Loading: [HekaFramingSplitter]
2015/08/19 16:10:28 Loading: [string-input-decoder]
2015/08/19 16:10:28 Loading: [PayloadEncoder]
2015/08/19 16:10:28 Loading: [TcpInput]
2015/08/19 16:10:28 Loading: [LogOutput]
2015/08/19 16:10:28 Loading: [DashboardOutput]
2015/08/19 16:10:28 Starting hekad...
2015/08/19 16:10:28 Output started: LogOutput
2015/08/19 16:10:28 Output started: DashboardOutput
2015/08/19 16:10:28 MessageRouter started.
2015/08/19 16:10:28 Input started: TcpInput
2015/08/19 16:10:30 Decoder 'TcpInput-string-input-decoder-127.0.0.1': stopped
```

My second try was this:
```
[hekad]
maxprocs = 2

[TcpInput]
address = ":514"
decoder = "RsyslogDecoder"

[RsyslogDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/rsyslog.lua"

[RsyslogDecoder.config]
type = "RSYSLOG_TraditionalFileFormat"
template = '%msg%'

[PayloadEncoder]
append_newlines = false

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"
```

But this works neither. 

Could someone enlighten me how to configure heka to ingest string via TCP?
Alternatively log event using `logger` (via TCP or /dev/kmsg).

Cheers
Christian

**Comment by ChristianKniep** [comment]
It might expect the message to be protobuf, but that's not quite clear to me.

**Comment by timurb** [comment]
Hi @ChristianKniep 

I think you need to use some kind of Splitter in addition to Decoder. Not quite sure right away which one as I'm quite new to Heka like you are.
You better ask such questions in mailing list, github is only for bugreports: https://mail.mozilla.org/listinfo/heka

**Comment by rafrombrc** [comment]
@timurb had it right. TcpInput defaults to using the [HekaFramingSplitter](http://hekad.readthedocs.org/en/v0.10.0b1/config/splitters/heka_framing.html), which expectsthe protobuf-based record delimiter that wraps native Heka streams. You're going to want [TokenSplitter](http://hekad.readthedocs.org/en/v0.10.0b1/config/splitters/token.html) to split on newlines or [RegexSplitter](http://hekad.readthedocs.org/en/v0.10.0b1/config/splitters/regex.html) for multi-line records.

**Comment by rafrombrc** [comment]
And yes, mailing list is a better venue. Thanks. :)

**Comment by ChristianKniep** [comment]
Just to close the issue with the HelloTCP config:
```# cat /etc/heka/hekad.toml
[hekad]
maxprocs = 2

[TcpInput]
address = ":5514"
splitter = "newline_splitter"
decoder = "better_decoder"

[newline_splitter]
type = "TokenSplitter"
delimiter = '\n'

[better_decoder]
type = "ScribbleDecoder"
    [better_decoder.message_fields]
    Type = "MyType"

[gross_decoder]
type = "PayloadRegexDecoder"
match_regex = "^(?P<Message>.+)"

[PayloadEncoder]
append_newlines = true

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"```
