### ISSUE TITLE
Heka is dropping a configured filter

### ISSUE THREAD

**Issue by drsnyder** [mozilla-services/heka#1690]
We have a problem where heka is dropping a filter without any warning or logging. The filter configuration is provided below.

I don't have any insight into when/why this is happening. It appears that heka will run fine for a few days and then suddenly drop the filter and stop sending the data to influxdb.

I know that it drops the filter because it no longer shows up in the "Filter" section of the dashboard UI. I also monitor the network traffic with the influxdb host to confirm that it's no longer sending data. Restarting heka resolves the issue.

There is a steady stream of nginx logs 24/7/365. Somewhere on the order of 100s to 1000s per minute.

It would be nice if:
 * logging could be added around why the filter was dropped
 * ideally heka recovers from whatever went wrong and continues to send the metrics

Configuration:
```
#Retrieves nginex access logs
[nginx_access_logs]
type = "LogstreamerInput"
splitter = "TokenSplitter"
decoder = "nginx_access_decoder"
log_directory = "/var/log/nginx"
file_match = 'api-gateway.access\.log\.?(?P<Index>\d+)?(.gz)?'
priority = ["^Index"]

#Parses nginex access logs to retrieve data about requests and their times
[nginx_access_decoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_access.lua"

[nginx_access_decoder.config]
log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent $request_length $request_time "$http_referer" "$http_user_agent" "$gzip_ratio"'
type = "nginx.access"

#Encodes data in the json format supported by InfluxDB
[schema_influx_encoder]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx.lua"
[schema_influx_encoder.config]
series = "api_gateway_%{Logger}"
skip_fields = "Type Payload Pid Logger EnvVersion remote_user http_referer"
represent_time_in_seconds = true

[NginxStatsAggregator]
type = "SandboxFilter"
message_matcher = "Type == 'nginx.access'"
ticker_interval = 1
filename = "/etc/heka/src/aggregate_gateway_stats.lua"

#Sends data through http to InfluxDB
[influx_nginx]
type = "HttpOutput"
message_matcher = "Type == 'heka.sandbox.nginx.aggregated'"
address = "http://influx:8086/db/site/series"
encoder = "schema_influx_encoder"
username = "username"
password = "password"
```

**Comment by rafrombrc** [comment]
Is there anything showing up in the "Termination Reports" section of your dashboard UI?

**Comment by drsnyder** [comment]
Hi Rob, Yes, I discovered that output today. There was a termination report indicating that `aggregate_gateway_stats.lua` failed with an error.

I also discovered the `can_exit` setting. I'm testing setting it to `false` in the `NginxStatsAggregator ` block above to see if that fixes it. It's hasn't failed since I made that change so I don't know if that will fix it or not.

Sorry :blush:, this may have been better suited to the mailing list.

**Comment by rafrombrc** [comment]
Setting `can_exit` to false means that Heka itself will shut down if the filter exits, which unfortunately is probably not what you want. Some of Heka's plugins support restarting if they fail, but that hasn't been added to the sandbox plugins. :P

**Comment by drsnyder** [comment]
Well we decided to try this (setting `can_exit` to false) and allow upstart to restart heka when this happens. It's not ideal but until restart support is added to the sandbox plugins I'm not sure what else we can do. Do you have any suggestions?

**Comment by rafrombrc** [comment]
No, that's your best bet. Be great if you could open a bug re: adding restart support to the SandboxFilter though, so we don't forget about it.

Anyway, closing this issue since it seems like both of your initial questions were answered.

**Comment by drsnyder** [comment]
Done! See #1692. 

Thanks!
