### ISSUE TITLE
After the build is complete, how to not to be clean

### ISSUE THREAD

**Issue by swan-go** [mozilla-services/heka#1697]
After the build is complete, how to not to be clean; because of need to see them; 
eg: the file /mozilla-services/heka/message/message_matcher_parser.go; 
eg: the directory mozilla-services/heka/pipelinemock 

thanks

**Comment by rafrombrc** [comment]
All of the files that are not in source control but are instead generated by the build are available in the `build` directory after a successful build. So if the Heka repo is checked out to `/mozilla-services/heka`, then message_matcher_parser.go will be available at `/mozilla-services/heka/build/heka/src/github.com/mozilla-services/heka/message/message_matcher_parser.go`.
