### ISSUE TITLE
Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request, but curl url is ok

### ISSUE THREAD

**Issue by swan-go** [mozilla-services/heka#1700]
oh, I have a another problem, need help. Thanks.
Heka version is 0.10.0b1

root@heka:~# curl 192.168.199.12:8473
{
  "status" : 200,
  "name" : "node_ccc_dev_client-02",
  "cluster_name" : "cluster_elasticsearch_ccc_dev",
  "version" : {
    "number" : "1.7.1",
    "build_hash" : "b88f43fc40b0bcd7f173a1f9ee2e97816de80b19",
    "build_timestamp" : "2015-07-29T09:54:16Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

The detail is in following:

2015/09/02 09:18:29 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:18:30 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:18:33 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:18:39 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:18:40 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:18:40 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:18:40 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:18:40 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:18:40 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:18:40 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:18:42 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:26:04 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:26:08 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:26:09 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:26:11 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:26:15 Plugin 'ElasticSearchOutput' error: HTTP response error status: 400 Bad Request
2015/09/02 09:26:15 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:26:17 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:26:17 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:26:17 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:26:17 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:26:17 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error
2015/09/02 09:26:17 Plugin 'ElasticSearchOutput' error: HTTP response error status: 500 Internal Server Error

**Comment by rafrombrc** [comment]
I'm afraid there's not nearly enough information here for us to be able to help.
