### ISSUE TITLE
CHANGES.txt should mention buffer configuration changes

### ISSUE THREAD

**Issue by sathieu** [mozilla-services/heka#1732]
Hello,

In TcpOutput:
* `queue_max_buffer_size` is now `max_file_size` in the buffering subsection
* `queue_full_action` is now `full_action` in the buffering subsection

There may be more...

**Comment by rafrombrc** [comment]
`queue_max_buffer_size` is replaced by `max_buffer_size`... `max_file_size` is something else. Even so, point taken, updated in c0122d6.
