### ISSUE TITLE
Does inject_payload() lead to OOM in Sandbox?

### ISSUE THREAD

**Issue by zstyblik** [mozilla-services/heka#1765]
Hello,

I wonder what I'm doing wrong or whether I'm using Heka in a way it's not supposed to be used or whether it's a bug.

Configuration:

```
[AMQPOutput]
message_matcher = "Type == 'heka.httpdata.request'"
encoder = "raw_payload"
url = "amqp://XXX"
exchange = "amq.topic"
exchange_type = "topic"
exchange_durability = true
exchange_auto_delete = false
routing_key = "myroutingkey"
content_type = "application/json"
use_framing = false

```

Lua encoder:

```
require "string"

function process_message()
  // Payload is expected to be a dumped JSON
  local raw_message = read_message("Payload")
  inject_payload("json", "", raw_message)
  return 0
end
```

In Heka 0.9.2 I can see `Plugin 'AMQPOutput' error: Error encoding message: FATAL: process_message() not enough memory`. However, in Heka 0.10.0b1 AMQP traffic just stops. Messages are still being processed, I can see that in Dashboard, but they're not being published to AMQP. When default encoder, which is ProtoBuf, for AMQP is used, everything works as expected(although it doesn't, because I expect LUA encoder to work). And since AMQP Output works with ProtoBuf, I'm not sure whether AMQP Output is to blame or not. I mean, sure it can be bug in AMQP Output as well.
I have tried this and that, but I have been pretty much unsuccessful.

Please, advise what I'm doing wrong.

Thank you,
Z.

**Comment by trink** [comment]
Increase the `output_limit` configuration for the encoder.  The encoder is being terminated and you are hitting bug https://github.com/mozilla-services/heka/issues/1038

**Comment by zstyblik** [comment]
I see. I'm fairly sure I've tried that, however it only prolonged the time before the inevitable. I have added the following and it's still going after 6M processed messages.

```
output_limit = 10240000          
memory_limit = 10240000
```

So I guess you're right and with #1763 clarified and my eyes open, I guess I wasn't adding enough before.

One more thing, though. Please, can you explain to me why no error message has been printed? Is that expected?

Thanks,
Z.
