### ISSUE TITLE
change output format for linux_netdev

### ISSUE THREAD

**Issue by timurb** [mozilla-services/heka#1767]
There is a decoder for netdev stats (https://github.com/mozilla-services/heka/blob/dev/sandbox/lua/decoders/linux_netdev.lua) which produces metrics in the format like
```
    | name:"lo_transmit_carrier" type:integer value:0
    | name:"eth0_receive_fifo" type:integer value:0
    | name:"lo_transmit_bytes" type:integer value:50278
    | name:"lo_receive_multicast" type:integer value:0
    | name:"eth0_receive_packets" type:integer value:0
    | name:"lo_transmit_compressed" type:integer value:0
    | name:"eth0_transmit_packets" type:integer value:0
    | name:"lo_transmit_colls" type:integer value:0
```

While it is probably fine for use in Graphite it looks like in Heka it would be mode natural to show up in 2 messages:
```
Message1:
    | name:"transmit_carrier" type:integer value:0
    | name:"transmit_bytes" type:integer value:50278
    | name:"receive_multicast" type:integer value:0
    | name:"transmit_compressed" type:integer value:0
    | name:"transmit_colls" type:integer value:0
    | name:"netdevice" type:string value:"lo"

Message2:
    | name:"receive_fifo" type:integer value:0
    | name:"receive_packets" type:integer value:0
    | name:"transmit_packets" type:integer value:0
    | name:"netdevice" type:string value:"eth0"
```

Will you be willing to accept pull request for that?
We've already got the fix implemented but this could break some existing installations, how should we handle this?

Another question: what field should hold name of network device? Is `netdevice` ok or we should name it otherwise?

**Comment by sathieu** [comment]
Create a PR, we'll discuss there.
It would be good to have an option to allow both ways.

**Comment by timurb** [comment]
Ok, created pull request of what we have now
