### ISSUE TITLE
ElasticsearchOutput ：Http 400 error Failed to derive xcontent from org.elasticsearch.common.bytes.BytesArray@1

### ISSUE THREAD

**Issue by guluglu** [mozilla-services/heka#1783]
I met the http 400 bad request in using ElasticsearchOutput.  
I test a 300,000lines log file ,there is always ten http 400error. And flush_count set to n. The contents in Elasticsearch will decrease 10*n. Alter wrote the result of  EsjsonEncoder to a file .I found there is 29,999 correct data like
{"index":{"_index":"elasticsearch","_type":"logsave"}}
{"Logger":"logfile","Time":"2015-08-26 01:05:22","Process":"8285","Handler":"common.rpc.common","Message":"Creating proxy for topic: q-plugin.node","Level":"INFO"}
 

Change flush_count 10 to 50 ,the count of missing log in Elasticsearch will from 100(10 multiply 10) to 500(10 multiply 50). Like thar every 30,000 lines will triger a log missing of  number flush_count

Below is EsOutput configs:

[ESJsonEncoder]
index = "elasticsearch"
type_name = "logsave"
fields = ["Logger","DynamicFields"]
dynamic_fields = ["Time","Process","Level","Handler","Message"]

[ESJsonEncoder.field_mappings]
Logger = "Logger"

[ElasticSearchOutput]
message_matcher = "Type == 'testfile'"
encoder = "ESJsonEncoder"
flush_interval = 1000
flush_count = 1000
server = "http://localhost:9200"

**Comment by guluglu** [comment]
11 wrong data appear  in the encoder file about every 30,000 bulk request

**Comment by guluglu** [comment]
If increase flush_interval to large enough, no http error and no missing logs in Elasticsearch

**Comment by guluglu** [comment]
the larger flush_interval is ,  less http error appear

**Comment by rafrombrc** [comment]
Closed in #1795.
