### ISSUE TITLE
what's heka's behavior if there is an input without any output

### ISSUE THREAD

**Issue by liaosiwei** [mozilla-services/heka#1785]
It seems to me that the documents don't  explain this situation when heka gets input data but there is no output to send the data. For an example, let's say I have a LogStreamInput and set the output to a influx server, but the influx server is down, So the data collected by heka will never send successfully and the data will be pending in the buffer and never be destroyed then the memory will never get recycled. If so, the memory will expand as the input collecting the data.

I did some test with an logstreaminput and an influx output that influx server is down using lua_encoders/schema_influx_line.lua. It gives me some results as:
<pre><code>
63 packs have been idle more than 120 seconds.
(input) Plugin names and quantities found on idle packs:
</code></pre>

What heka will behave in this situation? Will heka get pending collecting data from input or something else?

**Comment by simonpasquier** [comment]
You'd need to configure buffering for your HTTP output plugin to avoid this issue. Please have a look at the [buffering](http://hekad.readthedocs.org/en/v0.10.0b2/buffering.html) documentation.

**Comment by rafrombrc** [comment]
Please use the mailing list for support questions; the issue tracker is meant for tracking bug reports and feature requests.
