### ISSUE TITLE
Heka doesn't rotate disk buffers on disk 

### ISSUE THREAD

**Issue by timurb** [mozilla-services/heka#1790]
I’m using TCPOutput to relay data to another Heka instance and I quite often see that a on-disk
buffer grows too much (within dozen of Gbs with default settings).

```
/var/cache/hekad/output_queue/relay_output# ls -l
total 9784788
-rw-r--r-- 1 root root 10019573004 Oct 31 17:37 30.log
-rw-r--r-- 1 root root          14 Oct 31 17:37 checkpoint.txt
root at r-jp-cms:/var/cache/hekad/output_queue/relay_output# cat checkpoint.txt
30 10019808619
```

At the same time I see the metrics emitted from this host by this output as I actually get alerted on them which helped me to find this.
After I restart Heka the file is deleted and another logfile starts to grow from zero.

Here is a section from my config file for relay_output:

```
[relay_output]
type = "TcpOutput"
address = "my.secret.domain:9123"
message_matcher = "TRUE"
```
I have no section for buffering for this plugin (nor for any other plugin) and have no other TcpOutputs.

I’m running Heka 0.10.0b1 from GH releases page on Ubuntu 12.04 on AWS.

Update: https://github.com/mozilla-services/heka/issues/1738 looks to fix the issue but I've decided to post it here for completeness.

**Comment by rafrombrc** [comment]
This issue has been resolved on the versions/0.10 branch, as of PR #1682. The fix will go out in the 0.10.0b2 release which I'm hoping to get out the door this week. Note that this is not actually related to the issue described in #1738, but that is being currently resolved and the fix will also be included in the 0.10.0b2 release.
