### ISSUE TITLE
Numbers not interpreted correctly in nginx decoder

### ISSUE THREAD

**Issue by gjuric** [mozilla-services/heka#1796]
$upstream_response_time variable should be 0.01 seconds, but it is encoded as 0 secods.

The same thing happens with larger numbers, like 0.49.

Log line:

    1.1.1.1 - - [22/Nov/2015:23:48:16 +0000] "POST /includes/process.php?action=update HTTP/2.0" 302 285 "https://HOST/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0" "-" "0.001"

Decoded as:

    :Timestamp: 2015-11-22 23:48:16 +0000 UTC
    :Type: nginx.access
    :Hostname: HOST
    :Pid: 0
    :Uuid: 6e74be42-1a31-43e3-a5db-34dbe7af4d4b
    :Logger: nginx_access_logs
    :Payload:
    :EnvVersion:
    :Severity: 7
    :Fields:
        | name:"upstream_response_time" type:double value:0 representation:"s"
        | name:"remote_user" type:string value:"-"
        | name:"http_referer" type:string value:"https://HOST/index.php"
        | name:"body_bytes_sent" type:double value:285 representation:"B"
        | name:"remote_addr" type:string value:"1.1.1.1" representation:"ipv4"
        | name:"status" type:double value:302
        | name:"http_user_agent" type:string value:"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
        | name:"request" type:string value:"POST /includes/process.php?action=update HTTP/2.0"

heka config:

    [nginx_access_decoder]
    type = "SandboxDecoder"
    filename = "lua_decoders/nginx_access.lua"

        [nginx_access_decoder.config]
        log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$upstream_response_time"'
        type = "nginx.access"

**Comment by trink** [comment]
The grammar works correctly for me http://lpeg.trink.com/share/77943009734676465 what version of Heka are you using?

**Comment by gjuric** [comment]
The latest, 0.10.0 Beta 2

**Comment by trink** [comment]
The array should be keyed with 'value' for Heka to work with that result I will update the grammar.

**Comment by trink** [comment]
Your config/data works for me on 0.10.0 Beta 2
```
2015/11/22 16:50:17 
:Timestamp: 2015-11-22 23:48:16 +0000 UTC
:Type: nginx.access
:Hostname: trink-x230
:Pid: 0
:Uuid: f290b94e-1523-4bce-a12d-85495528a8d4
:Logger: LogstreamerInput
:Payload: 
:EnvVersion: 
:Severity: 7
:Fields:
    | name:"upstream_response_time" type:double value:0.001 representation:"s"
    | name:"remote_user" type:string value:"-"
    | name:"http_x_forwarded_for" type:string value:"-"
    | name:"http_referer" type:string value:"https://HOST/index.php"
    | name:"body_bytes_sent" type:double value:285 representation:"B"
    | name:"remote_addr" type:string value:"1.1.1.1" representation:"ipv4"
    | name:"status" type:double value:302
    | name:"http_user_agent" type:string value:"Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"
    | name:"request" type:string value:"POST /includes/process.php?action=update HTTP/2.0"
```

**Comment by trink** [comment]
Did you build from source or use the prebuilt package?

**Comment by gjuric** [comment]
Prebuilt package, 64bit.deb. I will double check the config tomorrow.

**Comment by gjuric** [comment]
Sorry, my bad, I had "$http_x_forwarded_for" in the nginx.log so heka was processing a "-" instead of "0.01".
