### ISSUE TITLE
Decoding doesn't work if I do not quote variables

### ISSUE THREAD

**Issue by gjuric** [mozilla-services/heka#1797]
I am watching an nginx access log, that looks like this:

    1.1.1.1 - - [22/Nov/2015:23:48:16 +0000] "POST /includes/process.php?action=update HTTP/2.0" 302 285 "https://HOST/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0" "-" 0.001

This is my log_format line

    log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$upstream_response_time"'

If I remove the quotes in log_format from $upstream_response_time it looks like heka is not processing any log lines. I have turned on a LogOutput output with message_matcher set to "TRUE" but I am not seeing any messages. If I bring back the quotes then it works.

**Comment by trink** [comment]
I am not seeing that problem.  However that field can contains spaces so quotes are recommended)
