### ISSUE TITLE
LogstreamerInput read current postion in file

### ISSUE THREAD

**Issue by guluglu** [mozilla-services/heka#1801]
LogstreamerInput can read the newest file in a directory.But when there are many machine,the newest file is about 2~3g,the total amount is still too large.Is there any  way to read from the current postion in file not from the begin

**Comment by guluglu** [comment]
Like start_position(string, one of ["beginning", "end"]) setting in Logstash

**Comment by tclh123** [comment]
I need this feature too. related #1482
cc @rafrombrc

**Comment by rafrombrc** [comment]
Fixed in #1831. Thanks so much to @tclh123 for submitting the code. :)

**Comment by guluglu** [comment]
@rafrombrc  Hi, I test it, but it doesn't work when file is small than 500 bytes i.e. it  still read from begin though I set initial_tail as true

**Comment by tclh123** [comment]
@guluglu should be fixed in #1838
