### ISSUE TITLE
How to test filter in plugins?

### ISSUE THREAD

**Issue by TuziBen** [mozilla-services/heka#1803]
Hi
I am a new one to go and also as to heka. Right now I wrote a simple filter plugin and it worked well, but I failed to find useful information for writing a testing file.

Does there have some testing file for the example "host_filter.go" , or any suggestion for how to do the test?

Thanks.

**Comment by rafrombrc** [comment]
Support questions should be directed at the [mailing list](https://mail.mozilla.org/listinfo/heka), the issue tracker is for bug reports and feature requests.
