### ISSUE TITLE
LogstreamerInput use MAX_RECORD_SIZE to truncate a record, but queue_buffer use MAX_MESSAGE_SIZE to CreateHekaStream

### ISSUE THREAD

**Issue by tianlin** [mozilla-services/heka#1805]
Is it a bug? I found LogstreamerInput use MAX_RECORD_SIZE to truncate a record, but queue_buffer use MAX_MESSAGE_SIZE(which is less than MAX_RECORD_SIZE) to CreateHekaStream.

Then hekad output is like this:
2015/12/02 17:42:15 Input 'out_logs_test_test' error: record exceeded MAX_RECORD_SIZE 948834 and was truncated

2015/12/02 17:42:15 Plugin 'SleepFilter' error: message framing error: Message too big, requires 948968 (MAX_MESSAGE_SIZE = 948576). logger: elis-smp-las..dmz..172.30.16.137..a.out. payload:

**Comment by rafrombrc** [comment]
No, this is correct. MAX_RECORD_SIZE is MAX_MESSAGE_SIZE plus MAX_HEADER_SIZE, i.e. the maximum size of a framed message. When loading data from the outside world, as LogstreamerInput is doing, it may include framing, and the entire message/header combination needs to fit in the buffer. While flowing through Heka, however, there is no framing, so MAX_RECORD_SIZE is what applies. The queue_buffer code only deals with messages (no headers), so MAX_RECORD_SIZE is appropriate there.

**Comment by tianlin** [comment]
I don't think so, when I read text from LogstreamerInput, I want heka to truncate record for me, but when it truncate record by MAX_RECORD_SIZE, it will put the text to Message.Payload, this will cause queue_buffer can't send this truncated record.

**Comment by tianlin** [comment]
Or can you teach me how to handle it?
