### ISSUE TITLE
Add `separator` option to JsonDecoder

### ISSUE THREAD

**Issue by sbward** [mozilla-services/heka#1809]
JsonDecoder needs an option to change the separator character that's used to join nested keys together.  Currently the separator is hard-coded to be a dot (`.`).

This is important for users of Elasticsearch 2.0 because dots are no longer allowed in key names.  For that use case it's necessary to change the separator to something else, like an underscore.

At the time of this posting, JsonDecoder is implemented here: https://github.com/mozilla-services/heka/blob/dev/sandbox/lua/decoders/json.lua -- and the function that joins the keys together is here: https://github.com/mozilla-services/lua_sandbox/blob/35e2c211c0dcbe37c8a686033b4a57e18a28711c/modules/util.lua#L17

I recommend adding an optional argument to override the character and exposing it in JsonDecoder's option set.

Thank you! 😎

**Comment by ei-grad** [comment]
Imho it would be better if Elasticsearch JSON Encoder would translate nested keys into nested JSON objects.

**Comment by roddik** [comment]
Any updates on this? This issue renders heka unusable for any new setup, that logs with nested json, and uses up-to-date elasticsearch. Logstash has a dedot filter for this, and adding a new option as suggested by sbward is easy.

**Comment by nfnty** [comment]
I implemented `ESJsonEncoder` `field_name_substitute` for this: https://github.com/nfnty/heka/commit/7540517254371c8d17eda2020226481affcf6aec

I may send a PR later.

**Comment by rafrombrc** [comment]
Relevant: mozilla-services/lua_sandbox#118.
