### ISSUE TITLE
Building from source package not possible

### ISSUE THREAD

**Issue by moritzheiber** [mozilla-services/heka#1810]
It seems to source packages provided for the releases do not contain a `.git` subdirectory. Therefore, [the `cmake` instruction to initialize heka's submodules for building](https://github.com/mozilla-services/heka/blob/dev/CMakeLists.txt#L109) will fail.

It's not a huge issue, I might as well clone the repository at the exact same moment in time (hash) as the release was tagged at, but I thought I'd mention it.

**Comment by rafrombrc** [comment]
Yes, this is a known issue. Unfortunately, github automatically adds those "source tarball" links to each release, and AFAIK there's no way to remove them. If it were possible to remove the links altogether I'd definitely do it.
