### ISSUE TITLE
How should I use JSON data from Kafka to elasticsearch?

### ISSUE THREAD

**Issue by elain** [mozilla-services/heka#1813]
Hello, everyone, please.
I want to use Heka to read data from the Kafka, and then write to elasticsearch, the data I have in JSON is Kafka format, but I use Heka to read, it is the JSON Kafka data in a message field, as follows:

![11](https://cloud.githubusercontent.com/assets/3030333/11831505/cadb619c-a3e9-11e5-94b9-e12c306e7733.png)

But I would like to make the following format: (logstash)
![22](https://cloud.githubusercontent.com/assets/3030333/11831513/d65f279c-a3e9-11e5-8662-591492c8ba9b.png)

My configuration is as follows:(hekad version=0.10.0b2)
#######################################
[hekad]
maxprocs = 8
pid_file = '/var/log/heka.pid'
base_dir = "/run/shm/hekad"

[heka_kafka_input]
type = "KafkaInput"
topic = "ngx_log_other"
addrs = ["c3-b2c-b2cop-log-kafka01.bj:9092","c3-b2c-b2cop-log-kafka02.bj:9092","c3-b2c-b2cop-log-kafka03.bj:9092"]
group = "heka_input"
partition = 0
event_buffer_size = 100

[ESLogstashV0Encoder]
index = "ngx_log_test_heka-%{%Y.%m.%d}"
dynamic_fields = [""]
#fields = ["Timestamp","Payload"]
#use_message_type = true
es_index_from_timestamp = true
type_name = "kafka"

##[ESJsonEncoder]
##index = "ngx_log_test_heka-%{%Y.%m.%d}"
###fields = ["Timestamp","Payload"]
##es_index_from_timestamp = true
##type_name = "kafka"

[ElasticSearchOutput]
type = "ElasticSearchOutput"
server = "http://es01.xxx.com:9200"
message_matcher = "TRUE"
encoder = "ESLogstashV0Encoder"
flush_interval = 200
flush_count = 10
use_buffering = true
#######################################

**Comment by rafrombrc** [comment]
The issue tracker is for bug reports and feature requests. Support requests should be directed to the mailing list: https://mail.mozilla.org/listinfo/heka

Thanks.
