### ISSUE TITLE
CMake Error Building Heka on Windows 

### ISSUE THREAD

**Issue by cleslie** [mozilla-services/heka#1829]
Hi, I am trying to build heka from source on windows 7. Installed

 Getting the following error when running 'build.bat'

    -- The C compiler identification is GNU 5.1.0
    -- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe
    -- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Found Go: C:/Go/bin/go.exe (found suitable version "1.5.2", minimum required is "1.4")
    -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.5.1.windows.1")
    -- GeoIP.h was not found, GeoIP functionality will not be included in this build.
    -- sphinx-build was not found, the documentation will not be generated.
    CMake Error at cmake/externals.cmake:10 (message):
      patch not found
    Call Stack (most recent call first):
      CMakeLists.txt:106 (include)

    -- Configuring incomplete, errors occurred!
    See also "C:/Users/calumleslie/Desktop/FPSNotes/heka/heka/build/CMakeFiles/CMakeOutput.log". 

Installed:
* CMake 3.4.1
* Go 1.5.2
* Mercurial 3.6.3
* tdmgcc-5.1.0

Any ideas how to solve this problem?

**Comment by cleslie** [comment]
Solved the problem - externals.cmake was not picking up my git path correctly due to a faulty local install of git. Sorry for the hassle.

**Comment by majj** [comment]
happen again：

CMake Error at cmake/externals.cmake:10 (message):
  patch not found
Call Stack (most recent call first):
  CMakeLists.txt:109 (include)

**Comment by wangfeiping** [comment]
happen again：
Who can tell me how to solve this problem?
Thanks a lot!

**Comment by torbiak** [comment]
@wangfeiping: https://github.com/mozilla-services/heka/issues/1818#issue-123720748

The easiest workaround is to put `patch` in your `PATH`.

**Comment by wangfeiping** [comment]
@torbiak 
Thanks! I'm building Heka on Centos 6.6, I'll try it right now.

**Comment by SeeWei1985** [comment]
yum install patch is ok
