### ISSUE TITLE
Can't install built heka deb package.

### ISSUE THREAD

**Issue by YiuTerran** [mozilla-services/heka#1835]
I can run generated `hekad` binary file directly, but after run
```
source build.sh
make deb
sudo dpkg -i heka_0.10.0_amd64.deb
```
OS output:
```
dpkg: dependency problems prevent configuration of heka:
 heka depends on libc6-amd64 (>= 2.15).
```

However, if i install v0.10.0 directly from source, there is no this dependency at all. Is there something wrong?

**Comment by sathieu** [comment]
Which Debian version are you using?

**Comment by YiuTerran** [comment]
@sathieu The Release Version is `Linux Mint 17.2 Rafaela`, based on `Ubuntu 14.04 LTS`.

**Comment by sathieu** [comment]
@YiuTerran What is the output of ```aptitude search libc6~i --display-format "%p %v %V"```?

**Comment by YiuTerran** [comment]
@sathieu , the output is:
```bash
libc6                                              2.19-0ubuntu6. 2.19-0ubuntu6.
libc6:i386                                         2.19-0ubuntu6. 2.19-0ubuntu6.
libc6-amd64:i386                                   2.19-0ubuntu6. 2.19-0ubuntu6.
libc6-dev                                          2.19-0ubuntu6. 2.19-0ubuntu6.
libc6-dev:i386                                     2.19-0ubuntu6. 2.19-0ubuntu6.
libc6-dev-amd64:i386                               2.19-0ubuntu6. 2.19-0ubuntu6.
libc6-i386                                         2.19-0ubuntu6. 2.19-0ubuntu6.
```

**Comment by sathieu** [comment]
it looks like the build mixed things about multi-arch (libc6-amd64 is only available for i386 and x32).

As a workaround, try to build in a container with only the amd64 arch.

**Comment by YiuTerran** [comment]
OK, i will try. Thanks for your help.

**Comment by sathieu** [comment]
For reference, I can reproduce the issue.
```make deb``` works well, until doing ```apt-get install libc6-amd64:i386``` and ```make deb``` again.

This is probably a cpack issue (or debhelper, but it seems unlikely).

**Comment by sathieu** [comment]
CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES might be the cause:
```
# cmake --system-information  | grep LINK_DI
CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES "/usr/lib/gcc/x86_64-linux-gnu/4.9;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib"
CMAKE_C_IMPLICIT_LINK_DIRECTORIES "/usr/lib/gcc/x86_64-linux-gnu/4.9;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib"
CMAKE_PLATFORM_IMPLICIT_LINK_DIRECTORIES "/lib;/lib32;/lib64;/usr/lib;/usr/lib32;/usr/lib64"
```

I stop my investigation here, not knowing enough cmake.

**Comment by sathieu** [comment]
Actually, heka is linked against a lib in libc6-amd64:
```
# ldd bin/hekad 
	linux-vdso.so.1 (0x00007ffc0122f000)
	libluasandbox.so.0 => /heka/build/heka/bin/../lib/libluasandbox.so.0 (0x00007f1c01687000)
	libluasb.so.0 => /heka/build/heka/bin/../lib/libluasb.so.0 (0x00007f1c0144f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1c01244000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1c00f43000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1c00d26000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1c0097c000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f77117a000)
```
So, the problem is at link time probably.

**Comment by YiuTerran** [comment]
Maybe you are right. I reopen this issue.
For now i just build and scp the `build/heka/` folder to the server, it works fine. So, i prefer there is a bug somewhere.

**Comment by YiuTerran** [comment]
I should post this issue to `CMake`.

And to fix this problem, just remove `libc-amd64`.
