### ISSUE TITLE
the log need more error info

### ISSUE THREAD

**Issue by liuyangc3** [mozilla-services/heka#1846]
I got this error when start heka
```
2016/01/28 14:04:02 Error reading config: 1 errors loading plugins
```
I have no clue to do next

**Comment by rafrombrc** [comment]
I'm sure that if you look carefully through the rest of your startup log, you'll see that there is other text somewhere that explains in more detail what plugin is causing the error.

**Comment by rafrombrc** [comment]
To clarify, this message is generated at the end of the start up process, showing you a count of how many errors were generated. If you look through the earlier messages, you should see some output generated by the plugin that caused the error with more details about what the specific problem is.

**Comment by liuyangc3** [comment]
thanks
