### ISSUE TITLE
SandboxInput/SandboxOutput plugins missing ${SHARE_PATH}/lua_io_modules in lua load path

### ISSUE THREAD

**Issue by nathwill** [mozilla-services/heka#1866]
i just set up some redis SandboxInput and SandboxOutput plugins, and was surprised to see that the module_directory config exposed doesn't include lua_io_modules. It's easy enough to override, but seems like a bit of a gotcha for Sandbox plugin types that will always need to do I/O.

thoughts?

**Comment by joell** [comment]
I just got bitten by the same issue.  Is this by design (for reasons not yet apparent to us), or was it simply a mistake that slipped into a commit somewhere?
