### ISSUE TITLE
can heka support multiline merge like logstash?

### ISSUE THREAD

**Issue by shijiant** [mozilla-services/heka#1907]
i get same log like below,   can we merge this into one message use heka ？

[03-Jun-2013 13:15:29] PHP Fatal error:  Uncaught exception 'Leb_Exception' in /data1/www/bbs.xman.com/htdocs/framework/xbox/ufo.php:68
Stack trace:
#0 /data/www/bbs.xman.com/htdocs/framework/dao/abstract.php(299): Leb_Dao_Pdo->connect(Array, 'read')
#1 /data/www/bbs.xman.com/htdocs/framework/dao/pdo.php(108): Leb_Dao_Abstract->initConnect(false)
#2 /data/www/bbs.xman.com/htdocs/framework/dao/abstract.php(1123): Leb_Dao_Pdo->query('SELECT \* FROM `...')
#3 /data/www/bbs.xman.com/htdocs/framework/dao/abstract.php(1217): Leb_Dao_Abstract->select(Array)

**Comment by sathieu** [comment]
The dev branch has PatternGroupingSplitter (PR #1842).

Doc at: https://github.com/mozilla-services/heka/blob/dev/docs/source/config/splitters/pattern_grouping.rst

(not on readthedoc yet?)

**Comment by shijiant** [comment]
@sathieu  thanks

i found  the RegexSplitter is works for this  situation

**Comment by sathieu** [comment]
@shijiant Can you close this issue then?

Next time, send your questions to the mailing-list instead. Thanks
