### ISSUE TITLE
fatal error: luasandbox.h: No such file or directory

### ISSUE THREAD

**Issue by vit1251** [mozilla-services/heka#1918]
``` bash
[  0%] Built target copy_includes
Scanning dependencies of target luasandbox
[  1%] Building C object src/CMakeFiles/luasandbox.dir/luasandbox.c.o
cc1: error: /home/me/heka/build/ep_base/Build/lua_sandbox/ep_base/include: not a directory [-Werror]
/home/me/heka/build/ep_base/Source/lua_sandbox/src/luasandbox.c:9:24: fatal error: luasandbox.h: No such file or directory
cc1: all warnings being treated as errors
compilation terminated.
```

What I will install? It is lua5.3-dev?

**Comment by sathieu** [comment]
Similar to https://github.com/mozilla-services/lua_sandbox/pull/125#issuecomment-208508939?

**Comment by vit1251** [comment]
@sathieu and this similar task is resolve?

**Comment by sathieu** [comment]
it is solved on lua_sandbox HEAD, but probably not on other branches.

**Comment by vit1251** [comment]
@sathieu could you suggest working version ready to build? Now I was trying 0.10.0 and 0.9.2 with topic error on 0.10 with lua_sandbox and 0.9.2 does not found lua.h but I previously install lua5.3-dev

**Comment by sathieu** [comment]
@trink Can you backport the fixes?

@vit1251: Probably, use an older compiler or cmake, i.e use an older distribution.

**Comment by trink** [comment]
#1920

**Comment by vit1251** [comment]
> Probably, use an older compiler or cmake, i.e use an older distribution.

@sathieu No, I use modern version of Ubuntu 16.04 release from 21.04.2016 (release 7 day ago) and version of cmake is 3.5.1, lua is 5.3, gcc is 5.3.1.

@trink Your #1920 resolve the problem. Thanx.
