### ISSUE TITLE
Documentation wrong

### ISSUE THREAD

**Issue by vit1251** [mozilla-services/heka#1922]
Hello, I try to install last version from source code by your documentation on page http://hekad.readthedocs.org/en/v0.10.0/installing.html and I was broken on step 4.

You have no install Makefile to using make.

**Comment by rafrombrc** [comment]
After you run '. build.sh' from the root of the repo, then a 'build' directory containing a Makefile will be created. When the build finishes you will be in the the 'build' folder.

**Comment by vit1251** [comment]
Yep. I know about CMake processing,
but no words about this in documentation
and it may confuse.
