### ISSUE TITLE
removing the out of range checkpoint file and stopping

### ISSUE THREAD

**Issue by Hujinyong** [mozilla-services/heka#1940]
Heka run several minutes, then output the following error:

2016/05/30 11:40:43 Input 'ngx_log' error: removing the out of range checkpoint file and stopping

Following is my ElasticSearchOutput config:

[es_payload]
type = "SandboxEncoder"
filename = "lua_encoders/es_payload.lua"
[es_payload.config]
es_index_from_timestamp = true
index = "testnginx-2016-05-27"
type_name = "nginx_access"

[ElasticSearchOutput]
message_matcher = "TRUE"
server = "http://xxx.xxx.xxx.xxx:9200"
flush_interval = 1000
flush_count = 200
encoder = "es_payload"

**Comment by michaelgibson** [comment]
Please send support requests to the [mailing list](https://mail.mozilla.org/listinfo/heka) instead (and close this issue). Thanks
