### ISSUE TITLE
How to debug a lua decoder?

### ISSUE THREAD

**Issue by ZhangYet** [mozilla-services/heka#1942]
I fount it my decoder will crash in production environment. 
It throw err msg as below:

```
2016/05/31 01:05:05 Decoder 'erulb_input-ErulbLogDecoder' error: FATAL: process_message() /usr/share/haruka/erulb_log.lua:6: output_limit exceeded
```

But it works well in my test envionment.

SO, is there any method to get information of my decoder while running in production environment? I mean since io is disabled in decoder/encoder etc, I can't use io to gather infomation from my decoder.

**Comment by simonpasquier** [comment]
If you're just asking questions, please don't use GitHub issues but the Heka mailing list.

If you catch exceptions in your decoder, you can inject the exception message in the Heka pipeline and send it wherever you want:

```
local ok, msg = pcall(inject_message, ...)
if not ok then
  inject_payload("txt", "error", msg)
end
```

**Comment by ZhangYet** [comment]
Sorry for my bad habit. And this solves my problem. Thanks a lot
