### ISSUE TITLE
Hi, please tell me how long does TcpOutput plugin cache of the domain name? Thanks!

### ISSUE THREAD

**Issue by wangfeiping** [mozilla-services/heka#1962]
We modify the IP address of the domain name, if the TcpOutput plugin will automatically redirects to the new IP on?

Thanks alot!

**Comment by michaelgibson** [comment]
That has more to do with your domain's TTL settings in DNS and the local DNS caching(nscd?) for the system on which the heka daemon is running.
In any case, Heka does not cache DNS in any way.

Please send support requests to the [mailing list](https://mail.mozilla.org/listinfo/heka) instead (and close this issue). Thanks

**Comment by wangfeiping** [comment]
@michaelgibson  Thanks!
