### ISSUE TITLE
How to set the memory of sandbox for filters

### ISSUE THREAD

**Issue by SeeWei1985** [mozilla-services/heka#1977]

**Comment by robison** [comment]
[SomeFilter]
type = 'SandboxFilter'
memory_limit = 33554432

**Comment by SeeWei1985** [comment]
memory_limit (uint):
The number of bytes the sandbox is allowed to consume before being terminated (default 8MiB).

instruction_limit (uint):
The number of instructions the sandbox is allowed to execute during the process_message/timer_event functions before being terminated (default 1M).

output_limit (uint):
The number of bytes the sandbox output buffer can hold before being terminated (default 63KiB). Warning: messages exceeding 64KiB will generate an error and be discarded by the standard output plugins (File, TCP, UDP) since they exceed the maximum message size.

1) what is the meaning of instructions? Would you give some examples to explain this concept of instructions

2) output_limit  is the limit of size for one message, is right?
