### ISSUE TITLE
do we have statsd output

### ISSUE THREAD

**Issue by rmrf** [mozilla-services/heka#1980]
or tcp/udp output can do the same thing?

**Comment by michaelgibson** [comment]
Looks like there is one that is included as an external plugin but it's not documented.
Included in build here:
https://github.com/mozilla-services/heka/blob/dev/cmake/externals.cmake#L190

Source:
https://github.com/mozilla-services/heka-mozsvc-plugins/blob/dev/statsd.go

You can see a listing of other external plugins here:
https://github.com/mozilla-services/heka/wiki/Community-Plugins

Most are not included in the pre-built release so you would have to add them manually:
http://hekad.readthedocs.io/en/latest/installing.html#building-hekad-with-external-plugins

**Comment by rmrf** [comment]
OK, Thanks.
