### ISSUE TITLE
how to use memory_limit and instruction_limit 

### ISSUE THREAD

**Issue by SeeWei1985** [mozilla-services/heka#1982]
memory_limit (uint):
The number of bytes the sandbox is allowed to consume before being terminated (default 8MiB).

instruction_limit (uint):
The number of instructions the sandbox is allowed to execute during the process_message/timer_event functions before being terminated (default 1M).

The filter sandbox of my project will not generate outputs after being executed for a period of time such as one week. Maybe there is lost of data and my filter is used to calacute some statistical results such as pv and uv.

The parameters memory_limit & instruction_limit  can be used to solve my problem? And what is the meanning of instruction？

**Comment by sathieu** [comment]
When memory_limit or instruction_limit  is exceeded, the plugin is terminated with a message in the log.  Unless you have can_exit =true, this will terminate heka.

Those are thus not related to your problem.

Please close this issue, and ask future questions to the Mailing-list (the issue tracker is not for support request).

Thanks
