### ISSUE TITLE
How to rotate the output of heka ?

### ISSUE THREAD

**Issue by SeeWei1985** [mozilla-services/heka#1987]
type = "FileOutput"
message_matcher = "TRUE"
path = "/work/heka/tomls/logs/item.logs"
perm = "666"
flush_count = 10
flush_operator = "OR"
encoder = "RstEncoder"
rotation_interval=1

The above codes are right? If I wanna to generate output logs hourly.

**Comment by wpecker** [comment]
from client to service by heka
