### ISSUE TITLE
heka build lua-5_1_5 error

### ISSUE THREAD

**Issue by dujiancheng** [mozilla-services/heka#1992]
hi:
When I tried to build heka on centos 7,but got failed.when Clone into 'lua-5_1_5' Prompt for GitHub username password,but tell repository 'https://github.com/trink/lua.git/' not found.

Scanning dependencies of target lua_sandbox
[  0%] Creating directories for 'lua_sandbox'
[  1%] Performing download step (git clone) for 'lua_sandbox'
Cloning into 'lua_sandbox'...
Note: checking out '97331863d3e05d25131b786e3e9199e805b9b4ba'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 9733186... Add the missing lua_sax dependency on the luasandbox lib
[  2%] No patch step for 'lua_sandbox'
[  2%] Performing update step (git fetch) for 'lua_sandbox'
HEAD is now at 9733186... Add the missing lua_sax dependency on the luasandbox lib
[  2%] Performing configure step for 'lua_sandbox'
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1")
Doxygen was not found, the documentation pages will not be generated
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xxx/heka_src/heka_git_master/heka/build/ep_base/Build/lua_sandbox
[  2%] Performing build step for 'lua_sandbox'
Scanning dependencies of target copy_includes
[  0%] Built target copy_includes
Scanning dependencies of target lua-5_1_5
[  1%] Creating directories for 'lua-5_1_5'
[  2%] Performing download step (git clone) for 'lua-5_1_5'
Cloning into 'lua-5_1_5'...
Username for 'https://github.com': xxxx@gmail.com
Password for 'https://xxxxxx@gmail.com@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/trink/lua.git/' not found

**Comment by trink** [comment]
Heka is no longer supported see this thread https://github.com/mozilla-services/lua_sandbox/issues/209
