### ISSUE TITLE
Can't install heka in Ubuntu13.04

### ISSUE THREAD

**Issue by ghost** [mozilla-services/heka#404]
Hi, all!

We use ubuntu13.04, and we install Go lang use source code under /usr/local/go 
and I set the path like this

```
 export GOROOT=/usr/local/go
 export PATH=$PATH:$GOROOT/bin
```

```
# go version
go version go1.1.1 linux/amd64
```

after finished install golang, And install heka got a error

```
root@squidloganalyzer:~/heka# ./build.sh
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (message):
  Could NOT find Go (missing: GO_VERSION GO_PLATFORM GO_ARCH) (Required is at
  least version "1.1")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:291 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGo.cmake:32 (find_package_handle_standard_args)
  CMakeLists.txt:16 (find_package)


-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
```

Can anyone tell me. How can I install heka the right way?

**Comment by carlosvega** [comment]
> I encountered the same build error, and none of the suggested fixes worked. Eventually I fixed it by symlinking my go binary (/usr/local/go/bin/go) to /usr/bin/go:
> 
> sudo ln -s /usr/local/go/bin/go /usr/bin/go

Also, I installed go this way, with gmv

http://www.hostingadvice.com/how-to/install-golang-on-ubuntu/
