### ISSUE TITLE
statsd input and floating point values

### ISSUE THREAD

**Issue by brokenjacobs** [mozilla-services/heka#850]
This piece of software:
https://github.com/BrightcoveOS/Diamond/

Doesn't normalize to integer values for its statsd output. The spec referenced on the heka site:
https://github.com/b/statsd_spec
Claims:
"For compatibility all values should be integers in the range (-2^53^, 2^53^)."

Should isn't the same as an RFC MUST I would assume... Perhaps heka should accept these values? It doesn't generate an exception, but it does seem to break parsing, and give lots of 0 valued stats. Even for values properly coming in as integers.

**Comment by rishid** [comment]
Any plans on getting this merged?

**Comment by rafrombrc** [comment]
Apologies for dropping the ball on responding to this. No, there's no reason for not allowing gauges to be floats, other than lack of awareness of the original author of this code (i.e. me). I'd be happy to give this a review if it gets opened as a PR. Please don't forget to update the CHANGES.txt file.

Thanks!

**Comment by alexzorin** [comment]
I can't speak to the correctness of my workaround, only to say that it has worked for me for the past few months.

Would appreciate someone who knows what they're doing to take a look
