### ISSUE TITLE
Add zlib compression/decompression to lua sandbox

### ISSUE THREAD

**Issue by michaelgibson** [mozilla-services/heka#857]
I'd like the ability to decompress messages using zlib.
Currently lua does not seem to have this natively built in and will require a third party interface.
This one looks fairly maintained.
https://github.com/brimworks/lua-zlib

Looking into how to integrate it into the build.
Looks like currently all third-party lua modules are referenced from 
https://github.com/mozilla-services/lua_sandbox/

Is that where we should be adding new modules rather than heka itself?

**Comment by trink** [comment]
Guess what the telemetry team needs/requested...
@michaelgibson did you do any performance testing

**Comment by michaelgibson** [comment]
I never did get this working using Lua so still using a Go based solution.

This is what I came up with for compression:
Using this StreamAggregatorFilter  
https://github.com/michaelgibson/heka-stream-aggregator#streamaggregatorfilter
In combination with the ZlibEncoder
https://github.com/michaelgibson/heka-zlib#zlibencoder

And Decompression using ZlibDecoder
https://github.com/michaelgibson/heka-zlib#zlibdecoder
In combination with the StreamSplitterDecoder
https://github.com/michaelgibson/heka-stream-aggregator#streamsplitterdecoder

I don't have anything for performance metrics for this either however. Using vs not using compression(for log aggregation) meant the difference between a slight increase in bandwith usage and completely saturating our link. That was more important at the time than how much extra overhead it was causing the process.
The code is functional(for me) but I'm no GoDev.
It's by no means optimized nor necessarily the best approach.

**Comment by trink** [comment]
The new sandbox (in 0.9) allows the use of shared libraries; for gzip I can now just drop this .so https://github.com/vincasmiliunas/lua-gzip in the lua_modules directory.
