### ISSUE TITLE
TCPOutput message too big, with increasing record size in the error

### ISSUE THREAD

**Issue by brokenjacobs** [mozilla-services/heka#858]
In my logs I've got:

> 2014/05/22 20:03:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 66405)
> 2014/05/22 20:05:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 66405)
> 2014/05/22 20:07:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 66405)
> 2014/05/22 20:09:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 90234)
> 2014/05/22 20:11:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 104931)
> 2014/05/22 20:13:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 104928)
> 2014/05/22 20:15:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 104930)

And this goes for a while. I have one client sending via input that seems to be causing these errors. This is on 0.6 but not the most recent commit. (right before the encoder change).These things keep going eventually getting up to:

> 2014/05/23 03:11:29 Plugin 'TcpOutput' error: Message too big, requires 65794 (MAX_RECORD_SIZE = 106716)

I've tried searching around for what the issue could be. This is mostly stats traffic coming back. Any ideas? If I can find a way to reproduce this consistently I'll add more comments.

**Comment by AdeMiller** [comment]
Yes. You can set the `max_message_size` property in the global `[hekad]` section of your configuration.

> New in version 0.9.
>
> max_message_size (uint32):
> The maximum size (in bytes) of message can be sent during processing. Defaults to 64KiB.
