### ISSUE TITLE
Create ElasticSearch object mappings for heka ip4 representations

### ISSUE THREAD

**Issue by brokenjacobs** [mozilla-services/heka#886]
You can currently do this with dynamic templates in elastic search if you know what fields names to match, however it would be better if the ElasticSearchOutput could set this mapping based on the heka message representation.

Having the ip type set allows for range searches based on ip address, and is very handy for any data involving ip addresses.

**Comment by trixpan** [comment]
+1 to @lyrixx comment. 

This is an issue easily solved in ES if you use the correct technique (Indices templates as described). 

@rafrombrc Issue is candidate for closure.

**Comment by rafrombrc** [comment]
Yes, closing since the desired behaviour can be achieved w/ ElasticSearch config.
