### ISSUE TITLE
Add FileOutput file rotation

### ISSUE THREAD

**Issue by rafrombrc** [mozilla-services/heka#976]
We've had several requests for FileOutput to be able to do file rotation w/o the use of an external rotation tool, in part b/c less tools, and in part b/c Heka needs to get a HUP signal to actually notice that a file has been rotated out from under it, and the person running Heka doesn't always have access to when rotation has happened and when HUP needs to be sent.

**Comment by bbinet** [comment]
That is good news, I'm very interested in this feature.

If I understand correctly, it means we'll be able to create a new file every day?
So for example, does the FileOutput plugin would be able to generate the following file structure:
```
.
|-- 2014
|   `-- 12
|       |-- 29.log
|       |-- 30.log
|       `-- 31.log
`-- 2015
    `-- 01
        |-- 01.log
        `-- 02.log
```

Do you know what is the roadmap for this feature?
I'm not proficient with golang, but I can provide feedback and help test this feature.

**Comment by djamelfel** [comment]
I am also very interested by this feature.

Do you think it's will be possible to see it in the next release ?

**Comment by rafrombrc** [comment]
Probably not, alas... I believe @4r9h might take a look at this soon, but I don't know what the timing will be, and there are other issues that are higher priority that we're currently tackling.

**Comment by 4r9h** [comment]
@rafrombrc I'll try.... is there any eta for the next release?

**Comment by rafrombrc** [comment]
Targeting a 0.9 release by then end of next week, or first week of Feb at the latest.

**Comment by bbinet** [comment]
I would also like to see it in the next release, and that could be a good way for me to start with golang.
@4r9h if you plan to work on it before the next release, please go ahead, else I'd like to have a try.

@rafrombrc: do you have any requirements, guidance for this feature? for example what will the configuration look like? Do you want the rotation time interval to be configurable or should it be hardcoded to one day? how would you make the path to the output files configurable so that one could output a file tree as shown in my previous comment?

**Comment by 4r9h** [comment]
@bbinet I'll look into this today/tomorrow and i let you know if i can't make it or i'll take something else.
@rafrombrc it would be awesome if you could give some ideas about final features for this implementation/issue?

**Comment by rafrombrc** [comment]
Here are my thoughts on how this should work:

* We support a limited number of time intervals: hourly, every 4 hours, every 12 hours, or daily. I'm not married to that exact set, but what's important is that an interval goes evenly into 24 hours.
* If you use rotation, regardless of when you start Heka, the files will be named relative to midnight of the day. So if you pick hourly, file rotation happens on the hour, you don't end up rotating files at 42 minutes after every hour, or something like that. If you pick every 4 hours, it happens at midnight, 4am, 8am, 12pm, 4pm, 8pm, etc.
* If Heka starts and a file already exists for the current interval, the existing file should be appended to.
* If rotation is in use, then the output file name can support Go's [time.Format](http://golang.org/pkg/time/#Time.Format) syntax to embed timestamps in the filename. This should allow folks to do nested folders just by putting a path separator in the filename. So to achieve what @bbinet asked for above, you'd use a setting of `path = "2006/01/02.log"`.

I think this is useful enough w/o being so heavy as to force us to add a new dependency for parsing cron format, etc. Does this all make sense?

**Comment by 4r9h** [comment]
Sounds okay. I'll try to hack something asap (probably during the weekend).

On Thu, Jan 22, 2015 at 10:33 PM, Rob Miller <notifications@github.com>
wrote:

> Here are my thoughts on how this should work:
>
>    - We support a limited number of time intervals: hourly, every 4
>    hours, every 12 hours, or daily. I'm not married to that exact set, but
>    what's important is that an interval goes evenly into 24 hours.
>    - If you use rotation, regardless of when you start Heka, the files
>    will be named relative to midnight of the day. So if you pick hourly, file
>    rotation happens on the hour, you don't end up rotating files at 42 minutes
>    after every hour, or something like that. If you pick every 4 hours, it
>    happens at midnight, 4am, 8am, 12pm, 4pm, 8pm, etc.
>    - If Heka starts and a file already exists for the current interval,
>    the existing file should be appended to.
>    - If rotation is in use, then the output file name can support Go's
>    time.Format <http://golang.org/pkg/time/#Time.Format> syntax to embed
>    timestamps in the filename. This should allow folks to do nested folders
>    just by putting a path separator in the filename. So to achieve what
>    @bbinet <https://github.com/bbinet> asked for above, you'd use a
>    setting of path = "2006/01/02.log".
>
> I think this is useful enough w/o being so heavy as to force us to add a
> new dependency for parsing cron format, etc. Does this all make sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla-services/heka/issues/976#issuecomment-71103356>
> .
>



-- 
jarek@reijutsu:~$ fortune
You have Egyptian flu: you're going to be a mummy.
jarek@reijutsu:~$ fortune
You now have Asian Flu.

**Comment by bbinet** [comment]
Thanks @rafrombrc and @4r9h , it sounds good.
@4r9h: I'm happy to help and if you don't find time to work on it, please tell me as I can have a try early next week.

**Comment by 4r9h** [comment]
Hi @rafrombrc @bbinet, sorry for a sudden change of heart but i'll probably won't be able to make this feature before release in next week. I'll gladly take any task with longer eta.
I hope i didn't generated too much problems for you.

**Comment by bbinet** [comment]
Ok, I am starting to work on this right now: I hope I could send a PR before the 0.9 release.

**Comment by bbinet** [comment]
Here is the pull request: #1294.
I would be happy to apply any changes are needed so that it can be included in the next release.
