### ISSUE TITLE
heka fails to build

### ISSUE THREAD

**Issue by Dieterbe** [mozilla-services/heka#991]
complete log @ https://gist.github.com/Dieterbe/37a55e6ea6ae90a85d9f
tried: 'source build.sh' '. build.sh' in bash, and both (i think) in zsh
latest code, dev branch.
building https://github.com/mozilla-services/lua_sandbox by itself works fine.

cc @rafrombrc 

using cmake 3.0, which might be the problem

**Comment by trixpan** [comment]
@rafrombrc this should be closed.

Fixed on 34e576f0ef8294f56ecaac2b1cceea2eda5d07a5

**Comment by rafrombrc** [comment]
Thanks. This should be resolved as of #1388.
